// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MoatSessionHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandlePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PairingFrameChannelHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandlePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PairingSessionHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandlePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RingDriverHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandlePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SyncRequestSessionHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandlePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SyncSessionHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandlePtr;

  @protected
  MoatSessionHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          dynamic raw);

  @protected
  PairingFrameChannelHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          dynamic raw);

  @protected
  PairingSessionHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          dynamic raw);

  @protected
  RingDriverHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          dynamic raw);

  @protected
  SyncRequestSessionHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          dynamic raw);

  @protected
  SyncSessionHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          dynamic raw);

  @protected
  MoatSessionHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          dynamic raw);

  @protected
  PairingFrameChannelHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          dynamic raw);

  @protected
  PairingSessionHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          dynamic raw);

  @protected
  RingDriverHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          dynamic raw);

  @protected
  SyncRequestSessionHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          dynamic raw);

  @protected
  SyncSessionHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          dynamic raw);

  @protected
  MoatSessionHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          dynamic raw);

  @protected
  PairingFrameChannelHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          dynamic raw);

  @protected
  PairingSessionHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          dynamic raw);

  @protected
  RingDriverHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          dynamic raw);

  @protected
  SyncRequestSessionHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          dynamic raw);

  @protected
  SyncSessionHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BlobEncryptResult dco_decode_blob_encrypt_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PairingFrameChannelHandle
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          dynamic raw);

  @protected
  CredentialDto dco_decode_box_autoadd_credential_dto(dynamic raw);

  @protected
  EnrollDto dco_decode_box_autoadd_enroll_dto(dynamic raw);

  @protected
  EventDto dco_decode_box_autoadd_event_dto(dynamic raw);

  @protected
  InboxEventDto dco_decode_box_autoadd_inbox_event_dto(dynamic raw);

  @protected
  OfferedKpDto dco_decode_box_autoadd_offered_kp_dto(dynamic raw);

  @protected
  ReactionPayloadDto dco_decode_box_autoadd_reaction_payload_dto(dynamic raw);

  @protected
  RingCommandDto dco_decode_box_autoadd_ring_command_dto(dynamic raw);

  @protected
  SenderInfoDto dco_decode_box_autoadd_sender_info_dto(dynamic raw);

  @protected
  SyncFailureDto dco_decode_box_autoadd_sync_failure_dto(dynamic raw);

  @protected
  SyncTallyDto dco_decode_box_autoadd_sync_tally_dto(dynamic raw);

  @protected
  TickInputsDto dco_decode_box_autoadd_tick_inputs_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ConvInventoryDto dco_decode_conv_inventory_dto(dynamic raw);

  @protected
  ConvStateDto dco_decode_conv_state_dto(dynamic raw);

  @protected
  CredentialDto dco_decode_credential_dto(dynamic raw);

  @protected
  DecryptResultDto dco_decode_decrypt_result_dto(dynamic raw);

  @protected
  DecryptedPush dco_decode_decrypted_push(dynamic raw);

  @protected
  DrawbridgeChallengeSignature dco_decode_drawbridge_challenge_signature(
      dynamic raw);

  @protected
  EncryptResultDto dco_decode_encrypt_result_dto(dynamic raw);

  @protected
  EnrollDto dco_decode_enroll_dto(dynamic raw);

  @protected
  EventDto dco_decode_event_dto(dynamic raw);

  @protected
  EventKindDto dco_decode_event_kind_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GroupKindDto dco_decode_group_kind_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageProcessResult dco_decode_image_process_result(dynamic raw);

  @protected
  InboxEventDto dco_decode_inbox_event_dto(dynamic raw);

  @protected
  KeyPackageResult dco_decode_key_package_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConvStateDto> dco_decode_list_conv_state_dto(dynamic raw);

  @protected
  List<CredentialDto> dco_decode_list_credential_dto(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<OfferedKpDto> dco_decode_list_offered_kp_dto(dynamic raw);

  @protected
  List<OwnEventInputDto> dco_decode_list_own_event_input_dto(dynamic raw);

  @protected
  List<PairingCommandDto> dco_decode_list_pairing_command_dto(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RingCommandDto> dco_decode_list_ring_command_dto(dynamic raw);

  @protected
  List<SiblingInfoDto> dco_decode_list_sibling_info_dto(dynamic raw);

  @protected
  List<SiblingStealthDto> dco_decode_list_sibling_stealth_dto(dynamic raw);

  @protected
  List<SyncMessageDto> dco_decode_list_sync_message_dto(dynamic raw);

  @protected
  List<SyncOutputDto> dco_decode_list_sync_output_dto(dynamic raw);

  @protected
  List<SyncReactionDto> dco_decode_list_sync_reaction_dto(dynamic raw);

  @protected
  OfferedKpDto dco_decode_offered_kp_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PairingFrameChannelHandle?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          dynamic raw);

  @protected
  CredentialDto? dco_decode_opt_box_autoadd_credential_dto(dynamic raw);

  @protected
  EnrollDto? dco_decode_opt_box_autoadd_enroll_dto(dynamic raw);

  @protected
  InboxEventDto? dco_decode_opt_box_autoadd_inbox_event_dto(dynamic raw);

  @protected
  OfferedKpDto? dco_decode_opt_box_autoadd_offered_kp_dto(dynamic raw);

  @protected
  ReactionPayloadDto? dco_decode_opt_box_autoadd_reaction_payload_dto(
      dynamic raw);

  @protected
  RingCommandDto? dco_decode_opt_box_autoadd_ring_command_dto(dynamic raw);

  @protected
  SenderInfoDto? dco_decode_opt_box_autoadd_sender_info_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  OwnEventInputDto dco_decode_own_event_input_dto(dynamic raw);

  @protected
  PairingCommandDto dco_decode_pairing_command_dto(dynamic raw);

  @protected
  PairingPayloadDto dco_decode_pairing_payload_dto(dynamic raw);

  @protected
  PairingUiStateDto dco_decode_pairing_ui_state_dto(dynamic raw);

  @protected
  ReactionPayloadDto dco_decode_reaction_payload_dto(dynamic raw);

  @protected
  RingCommandDto dco_decode_ring_command_dto(dynamic raw);

  @protected
  RingMsgDto dco_decode_ring_msg_dto(dynamic raw);

  @protected
  SenderInfoDto dco_decode_sender_info_dto(dynamic raw);

  @protected
  SiblingInfoDto dco_decode_sibling_info_dto(dynamic raw);

  @protected
  SiblingStealthDto dco_decode_sibling_stealth_dto(dynamic raw);

  @protected
  StealthKeypair dco_decode_stealth_keypair(dynamic raw);

  @protected
  SyncFailureDto dco_decode_sync_failure_dto(dynamic raw);

  @protected
  SyncFrameDto dco_decode_sync_frame_dto(dynamic raw);

  @protected
  SyncMessageDto dco_decode_sync_message_dto(dynamic raw);

  @protected
  SyncOutputDto dco_decode_sync_output_dto(dynamic raw);

  @protected
  SyncProgressDto dco_decode_sync_progress_dto(dynamic raw);

  @protected
  SyncReactionDto dco_decode_sync_reaction_dto(dynamic raw);

  @protected
  SyncRequestUiStateDto dco_decode_sync_request_ui_state_dto(dynamic raw);

  @protected
  SyncTallyDto dco_decode_sync_tally_dto(dynamic raw);

  @protected
  ThumbHashResult dco_decode_thumb_hash_result(dynamic raw);

  @protected
  TickInputsDto dco_decode_tick_inputs_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WelcomeResultDto dco_decode_welcome_result_dto(dynamic raw);

  @protected
  MoatSessionHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          SseDeserializer deserializer);

  @protected
  PairingFrameChannelHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          SseDeserializer deserializer);

  @protected
  PairingSessionHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          SseDeserializer deserializer);

  @protected
  RingDriverHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          SseDeserializer deserializer);

  @protected
  SyncRequestSessionHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          SseDeserializer deserializer);

  @protected
  SyncSessionHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          SseDeserializer deserializer);

  @protected
  MoatSessionHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          SseDeserializer deserializer);

  @protected
  PairingFrameChannelHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          SseDeserializer deserializer);

  @protected
  PairingSessionHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          SseDeserializer deserializer);

  @protected
  RingDriverHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          SseDeserializer deserializer);

  @protected
  SyncRequestSessionHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          SseDeserializer deserializer);

  @protected
  SyncSessionHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          SseDeserializer deserializer);

  @protected
  MoatSessionHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          SseDeserializer deserializer);

  @protected
  PairingFrameChannelHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          SseDeserializer deserializer);

  @protected
  PairingSessionHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          SseDeserializer deserializer);

  @protected
  RingDriverHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          SseDeserializer deserializer);

  @protected
  SyncRequestSessionHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          SseDeserializer deserializer);

  @protected
  SyncSessionHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BlobEncryptResult sse_decode_blob_encrypt_result(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PairingFrameChannelHandle
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          SseDeserializer deserializer);

  @protected
  CredentialDto sse_decode_box_autoadd_credential_dto(
      SseDeserializer deserializer);

  @protected
  EnrollDto sse_decode_box_autoadd_enroll_dto(SseDeserializer deserializer);

  @protected
  EventDto sse_decode_box_autoadd_event_dto(SseDeserializer deserializer);

  @protected
  InboxEventDto sse_decode_box_autoadd_inbox_event_dto(
      SseDeserializer deserializer);

  @protected
  OfferedKpDto sse_decode_box_autoadd_offered_kp_dto(
      SseDeserializer deserializer);

  @protected
  ReactionPayloadDto sse_decode_box_autoadd_reaction_payload_dto(
      SseDeserializer deserializer);

  @protected
  RingCommandDto sse_decode_box_autoadd_ring_command_dto(
      SseDeserializer deserializer);

  @protected
  SenderInfoDto sse_decode_box_autoadd_sender_info_dto(
      SseDeserializer deserializer);

  @protected
  SyncFailureDto sse_decode_box_autoadd_sync_failure_dto(
      SseDeserializer deserializer);

  @protected
  SyncTallyDto sse_decode_box_autoadd_sync_tally_dto(
      SseDeserializer deserializer);

  @protected
  TickInputsDto sse_decode_box_autoadd_tick_inputs_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ConvInventoryDto sse_decode_conv_inventory_dto(SseDeserializer deserializer);

  @protected
  ConvStateDto sse_decode_conv_state_dto(SseDeserializer deserializer);

  @protected
  CredentialDto sse_decode_credential_dto(SseDeserializer deserializer);

  @protected
  DecryptResultDto sse_decode_decrypt_result_dto(SseDeserializer deserializer);

  @protected
  DecryptedPush sse_decode_decrypted_push(SseDeserializer deserializer);

  @protected
  DrawbridgeChallengeSignature sse_decode_drawbridge_challenge_signature(
      SseDeserializer deserializer);

  @protected
  EncryptResultDto sse_decode_encrypt_result_dto(SseDeserializer deserializer);

  @protected
  EnrollDto sse_decode_enroll_dto(SseDeserializer deserializer);

  @protected
  EventDto sse_decode_event_dto(SseDeserializer deserializer);

  @protected
  EventKindDto sse_decode_event_kind_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GroupKindDto sse_decode_group_kind_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageProcessResult sse_decode_image_process_result(
      SseDeserializer deserializer);

  @protected
  InboxEventDto sse_decode_inbox_event_dto(SseDeserializer deserializer);

  @protected
  KeyPackageResult sse_decode_key_package_result(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConvStateDto> sse_decode_list_conv_state_dto(
      SseDeserializer deserializer);

  @protected
  List<CredentialDto> sse_decode_list_credential_dto(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<OfferedKpDto> sse_decode_list_offered_kp_dto(
      SseDeserializer deserializer);

  @protected
  List<OwnEventInputDto> sse_decode_list_own_event_input_dto(
      SseDeserializer deserializer);

  @protected
  List<PairingCommandDto> sse_decode_list_pairing_command_dto(
      SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RingCommandDto> sse_decode_list_ring_command_dto(
      SseDeserializer deserializer);

  @protected
  List<SiblingInfoDto> sse_decode_list_sibling_info_dto(
      SseDeserializer deserializer);

  @protected
  List<SiblingStealthDto> sse_decode_list_sibling_stealth_dto(
      SseDeserializer deserializer);

  @protected
  List<SyncMessageDto> sse_decode_list_sync_message_dto(
      SseDeserializer deserializer);

  @protected
  List<SyncOutputDto> sse_decode_list_sync_output_dto(
      SseDeserializer deserializer);

  @protected
  List<SyncReactionDto> sse_decode_list_sync_reaction_dto(
      SseDeserializer deserializer);

  @protected
  OfferedKpDto sse_decode_offered_kp_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PairingFrameChannelHandle?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          SseDeserializer deserializer);

  @protected
  CredentialDto? sse_decode_opt_box_autoadd_credential_dto(
      SseDeserializer deserializer);

  @protected
  EnrollDto? sse_decode_opt_box_autoadd_enroll_dto(
      SseDeserializer deserializer);

  @protected
  InboxEventDto? sse_decode_opt_box_autoadd_inbox_event_dto(
      SseDeserializer deserializer);

  @protected
  OfferedKpDto? sse_decode_opt_box_autoadd_offered_kp_dto(
      SseDeserializer deserializer);

  @protected
  ReactionPayloadDto? sse_decode_opt_box_autoadd_reaction_payload_dto(
      SseDeserializer deserializer);

  @protected
  RingCommandDto? sse_decode_opt_box_autoadd_ring_command_dto(
      SseDeserializer deserializer);

  @protected
  SenderInfoDto? sse_decode_opt_box_autoadd_sender_info_dto(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OwnEventInputDto sse_decode_own_event_input_dto(SseDeserializer deserializer);

  @protected
  PairingCommandDto sse_decode_pairing_command_dto(
      SseDeserializer deserializer);

  @protected
  PairingPayloadDto sse_decode_pairing_payload_dto(
      SseDeserializer deserializer);

  @protected
  PairingUiStateDto sse_decode_pairing_ui_state_dto(
      SseDeserializer deserializer);

  @protected
  ReactionPayloadDto sse_decode_reaction_payload_dto(
      SseDeserializer deserializer);

  @protected
  RingCommandDto sse_decode_ring_command_dto(SseDeserializer deserializer);

  @protected
  RingMsgDto sse_decode_ring_msg_dto(SseDeserializer deserializer);

  @protected
  SenderInfoDto sse_decode_sender_info_dto(SseDeserializer deserializer);

  @protected
  SiblingInfoDto sse_decode_sibling_info_dto(SseDeserializer deserializer);

  @protected
  SiblingStealthDto sse_decode_sibling_stealth_dto(
      SseDeserializer deserializer);

  @protected
  StealthKeypair sse_decode_stealth_keypair(SseDeserializer deserializer);

  @protected
  SyncFailureDto sse_decode_sync_failure_dto(SseDeserializer deserializer);

  @protected
  SyncFrameDto sse_decode_sync_frame_dto(SseDeserializer deserializer);

  @protected
  SyncMessageDto sse_decode_sync_message_dto(SseDeserializer deserializer);

  @protected
  SyncOutputDto sse_decode_sync_output_dto(SseDeserializer deserializer);

  @protected
  SyncProgressDto sse_decode_sync_progress_dto(SseDeserializer deserializer);

  @protected
  SyncReactionDto sse_decode_sync_reaction_dto(SseDeserializer deserializer);

  @protected
  SyncRequestUiStateDto sse_decode_sync_request_ui_state_dto(
      SseDeserializer deserializer);

  @protected
  SyncTallyDto sse_decode_sync_tally_dto(SseDeserializer deserializer);

  @protected
  ThumbHashResult sse_decode_thumb_hash_result(SseDeserializer deserializer);

  @protected
  TickInputsDto sse_decode_tick_inputs_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WelcomeResultDto sse_decode_welcome_result_dto(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          MoatSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          PairingFrameChannelHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          PairingSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          RingDriverHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          SyncRequestSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          SyncSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          MoatSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          PairingFrameChannelHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          PairingSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          RingDriverHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          SyncRequestSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          SyncSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
          MoatSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          PairingFrameChannelHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
          PairingSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
          RingDriverHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
          SyncRequestSessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
          SyncSessionHandle self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_blob_encrypt_result(
      BlobEncryptResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          PairingFrameChannelHandle self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_credential_dto(
      CredentialDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_enroll_dto(
      EnrollDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_event_dto(
      EventDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_inbox_event_dto(
      InboxEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_offered_kp_dto(
      OfferedKpDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_reaction_payload_dto(
      ReactionPayloadDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ring_command_dto(
      RingCommandDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sender_info_dto(
      SenderInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_failure_dto(
      SyncFailureDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_tally_dto(
      SyncTallyDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tick_inputs_dto(
      TickInputsDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_conv_inventory_dto(
      ConvInventoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_conv_state_dto(ConvStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_credential_dto(CredentialDto self, SseSerializer serializer);

  @protected
  void sse_encode_decrypt_result_dto(
      DecryptResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_decrypted_push(DecryptedPush self, SseSerializer serializer);

  @protected
  void sse_encode_drawbridge_challenge_signature(
      DrawbridgeChallengeSignature self, SseSerializer serializer);

  @protected
  void sse_encode_encrypt_result_dto(
      EncryptResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_enroll_dto(EnrollDto self, SseSerializer serializer);

  @protected
  void sse_encode_event_dto(EventDto self, SseSerializer serializer);

  @protected
  void sse_encode_event_kind_dto(EventKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_group_kind_dto(GroupKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_process_result(
      ImageProcessResult self, SseSerializer serializer);

  @protected
  void sse_encode_inbox_event_dto(InboxEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_key_package_result(
      KeyPackageResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conv_state_dto(
      List<ConvStateDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_credential_dto(
      List<CredentialDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_offered_kp_dto(
      List<OfferedKpDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_own_event_input_dto(
      List<OwnEventInputDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pairing_command_dto(
      List<PairingCommandDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_ring_command_dto(
      List<RingCommandDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sibling_info_dto(
      List<SiblingInfoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sibling_stealth_dto(
      List<SiblingStealthDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sync_message_dto(
      List<SyncMessageDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sync_output_dto(
      List<SyncOutputDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sync_reaction_dto(
      List<SyncReactionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_offered_kp_dto(OfferedKpDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
          PairingFrameChannelHandle? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_credential_dto(
      CredentialDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_enroll_dto(
      EnrollDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_inbox_event_dto(
      InboxEventDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_offered_kp_dto(
      OfferedKpDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_reaction_payload_dto(
      ReactionPayloadDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ring_command_dto(
      RingCommandDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sender_info_dto(
      SenderInfoDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_own_event_input_dto(
      OwnEventInputDto self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_command_dto(
      PairingCommandDto self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_payload_dto(
      PairingPayloadDto self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_ui_state_dto(
      PairingUiStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_reaction_payload_dto(
      ReactionPayloadDto self, SseSerializer serializer);

  @protected
  void sse_encode_ring_command_dto(
      RingCommandDto self, SseSerializer serializer);

  @protected
  void sse_encode_ring_msg_dto(RingMsgDto self, SseSerializer serializer);

  @protected
  void sse_encode_sender_info_dto(SenderInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_sibling_info_dto(
      SiblingInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_sibling_stealth_dto(
      SiblingStealthDto self, SseSerializer serializer);

  @protected
  void sse_encode_stealth_keypair(
      StealthKeypair self, SseSerializer serializer);

  @protected
  void sse_encode_sync_failure_dto(
      SyncFailureDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_frame_dto(SyncFrameDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_message_dto(
      SyncMessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_output_dto(SyncOutputDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_progress_dto(
      SyncProgressDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_reaction_dto(
      SyncReactionDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_request_ui_state_dto(
      SyncRequestUiStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_tally_dto(SyncTallyDto self, SseSerializer serializer);

  @protected
  void sse_encode_thumb_hash_result(
      ThumbHashResult self, SseSerializer serializer);

  @protected
  void sse_encode_tick_inputs_dto(TickInputsDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_welcome_result_dto(
      WelcomeResultDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingFrameChannelHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRingDriverHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncRequestSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_moat_dart_common_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSyncSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
