package main

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"math/rand"
	"os"
	"strconv"
	"testing"
	"time"
)

// ── Cross-language test vectors ─────────────────────────────────

type ChallengeVector struct {
	Nonce        string `json:"nonce"`
	URL          string `json:"url"`
	Timestamp    int64  `json:"timestamp"`
	MessageHex   string `json:"message_hex"`
	PublicKeyB64 string `json:"public_key_b64"`
	SignatureB64 string `json:"signature_b64"`
}

// TestCrossLanguage_ChallengeVectors verifies that Ed25519 signatures
// generated by Rust's ed25519_dalek verify under Go's crypto/ed25519.
// This proves both sides construct the same signed message bytes.
func TestCrossLanguage_ChallengeVectors(t *testing.T) {
	data, err := os.ReadFile("testdata/challenge_vectors.json")
	if err != nil {
		t.Fatalf("failed to read test vectors: %v", err)
	}

	var vectors []ChallengeVector
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatalf("failed to parse test vectors: %v", err)
	}

	for i, v := range vectors {
		// Decode Rust-generated signature and public key
		pubKeyBytes, err := base64.StdEncoding.DecodeString(v.PublicKeyB64)
		if err != nil {
			t.Fatalf("vector %d: failed to decode public key: %v", i, err)
		}
		sigBytes, err := base64.StdEncoding.DecodeString(v.SignatureB64)
		if err != nil {
			t.Fatalf("vector %d: failed to decode signature: %v", i, err)
		}

		// Verify the Rust-generated signature using Go's crypto/ed25519
		if !ed25519.Verify(pubKeyBytes, mustDecodeHex(t, v.MessageHex), sigBytes) {
			t.Fatalf("vector %d: Rust-generated signature FAILED Go verification (nonce=%q url=%q ts=%d)",
				i, v.Nonce, v.URL, v.Timestamp)
		}

		// Also verify that Go constructs the same message bytes
		goMessage := verifyChallenge_buildMessage(v.Nonce, v.URL, v.Timestamp)
		goMessageHex := hex.EncodeToString(goMessage)
		if goMessageHex != v.MessageHex {
			t.Fatalf("vector %d: message format mismatch:\n  Go:   %s\n  Rust: %s",
				i, goMessageHex, v.MessageHex)
		}

		// And verify the signature against Go's constructed message
		if err := verifyChallenge(pubKeyBytes, v.Nonce, v.URL, v.Timestamp, sigBytes); err != nil {
			t.Fatalf("vector %d: verifyChallenge failed: %v", i, err)
		}
	}

	t.Logf("verified %d cross-language challenge vectors", len(vectors))
}

func mustDecodeHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("failed to decode hex: %v", err)
	}
	return b
}

// verifyChallenge_buildMessage extracts message construction for testing.
func verifyChallenge_buildMessage(nonce, relayURL string, timestamp int64) []byte {
	return []byte(nonce + "\n" + relayURL + "\n" + strconv.FormatInt(timestamp, 10) + "\n")
}

// ── update_tags with overlapping add/remove ─────────────────────

// (Moved to relay_prop_test.go as TestProp_UpdateTagsOverlap)

// ── Dedup cleanup removes stale entries ─────────────────────────

// Property: After cleanup, no entry in dedup is older than 5 seconds.
func TestProp_DedupCleanupRemovesStale(t *testing.T) {
	rng := rand.New(rand.NewSource(53))

	for i := 0; i < 50; i++ {
		env := newPropEnv()

		// Insert entries with various ages
		now := time.Now()
		numEntries := rng.Intn(20) + 1
		var expectedSurvivors int

		env.relay.dedupMu.Lock()
		for j := 0; j < numEntries; j++ {
			key := randomTag(rng) + ":" + randomTag(rng)
			ageSecs := rng.Intn(15) // 0-14 seconds old
			entryTime := now.Add(-time.Duration(ageSecs) * time.Second)
			env.relay.dedup[key] = entryTime

			if ageSecs <= 5 {
				expectedSurvivors++
			}
		}
		env.relay.dedupMu.Unlock()

		// Run cleanup
		env.relay.cleanupDedup()

		// Verify: no entry is older than 5 seconds
		env.relay.dedupMu.Lock()
		for key, entryTime := range env.relay.dedup {
			age := time.Since(entryTime)
			if age > 6*time.Second { // small buffer for test execution time
				t.Fatalf("iteration %d: dedup entry %q is %v old after cleanup", i, key, age)
			}
		}
		remaining := len(env.relay.dedup)
		env.relay.dedupMu.Unlock()

		if remaining > expectedSurvivors {
			t.Fatalf("iteration %d: expected at most %d survivors, got %d", i, expectedSurvivors, remaining)
		}
	}
}
