// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 112553158;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_moat_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<WelcomeResultDto> crateApiSimpleMoatSessionHandleAddMember({
    required MoatSessionHandle that,
    required List<int> groupId,
    required List<int> keyBundle,
    required List<int> newMemberKeyPackage,
  });

  Future<Uint8List> crateApiSimpleMoatSessionHandleCreateGroup({
    required MoatSessionHandle that,
    required String did,
    required String deviceName,
    required List<int> keyBundle,
  });

  Future<DecryptResultDto> crateApiSimpleMoatSessionHandleDecryptEvent({
    required MoatSessionHandle that,
    required List<int> groupId,
    required List<int> ciphertext,
  });

  Uint8List crateApiSimpleMoatSessionHandleDeviceId({
    required MoatSessionHandle that,
  });

  Future<EncryptResultDto> crateApiSimpleMoatSessionHandleEncryptEvent({
    required MoatSessionHandle that,
    required List<int> groupId,
    required List<int> keyBundle,
    required EventDto event,
  });

  Future<Uint8List> crateApiSimpleMoatSessionHandleExportState({
    required MoatSessionHandle that,
  });

  Future<MoatSessionHandle> crateApiSimpleMoatSessionHandleFromState({
    required List<int> state,
  });

  Future<KeyPackageResult> crateApiSimpleMoatSessionHandleGenerateKeyPackage({
    required MoatSessionHandle that,
    required String did,
    required String deviceName,
  });

  Future<List<String>> crateApiSimpleMoatSessionHandleGetGroupDids({
    required MoatSessionHandle that,
    required List<int> groupId,
  });

  Future<BigInt?> crateApiSimpleMoatSessionHandleGetGroupEpoch({
    required MoatSessionHandle that,
    required List<int> groupId,
  });

  bool crateApiSimpleMoatSessionHandleHasPendingChanges({
    required MoatSessionHandle that,
  });

  MoatSessionHandle crateApiSimpleMoatSessionHandleNewSession();

  Future<Uint8List> crateApiSimpleMoatSessionHandleProcessWelcome({
    required MoatSessionHandle that,
    required List<int> welcomeBytes,
  });

  Uint8List crateApiSimpleDeriveTag({
    required List<int> groupId,
    required BigInt epoch,
  });

  Future<Uint8List> crateApiSimpleEncryptForStealth({
    required List<Uint8List> recipientScanPubkeys,
    required List<int> welcomeBytes,
  });

  StealthKeypair crateApiSimpleGenerateStealthKeypair();

  Future<void> crateApiSimpleInitApp();

  Uint8List crateApiSimplePadToBucket({required List<int> plaintext});

  Uint8List? crateApiSimpleTryDecryptStealth({
    required List<int> scanPrivkey,
    required List<int> payload,
  });

  Uint8List crateApiSimpleUnpad({required List<int> padded});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MoatSessionHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MoatSessionHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MoatSessionHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<WelcomeResultDto> crateApiSimpleMoatSessionHandleAddMember({
    required MoatSessionHandle that,
    required List<int> groupId,
    required List<int> keyBundle,
    required List<int> newMemberKeyPackage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(keyBundle, serializer);
          sse_encode_list_prim_u_8_loose(newMemberKeyPackage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_welcome_result_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleAddMemberConstMeta,
        argValues: [that, groupId, keyBundle, newMemberKeyPackage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleAddMemberConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_add_member",
        argNames: ["that", "groupId", "keyBundle", "newMemberKeyPackage"],
      );

  @override
  Future<Uint8List> crateApiSimpleMoatSessionHandleCreateGroup({
    required MoatSessionHandle that,
    required String did,
    required String deviceName,
    required List<int> keyBundle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          sse_encode_String(did, serializer);
          sse_encode_String(deviceName, serializer);
          sse_encode_list_prim_u_8_loose(keyBundle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleCreateGroupConstMeta,
        argValues: [that, did, deviceName, keyBundle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleCreateGroupConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_create_group",
        argNames: ["that", "did", "deviceName", "keyBundle"],
      );

  @override
  Future<DecryptResultDto> crateApiSimpleMoatSessionHandleDecryptEvent({
    required MoatSessionHandle that,
    required List<int> groupId,
    required List<int> ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_decrypt_result_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleDecryptEventConstMeta,
        argValues: [that, groupId, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleDecryptEventConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_decrypt_event",
        argNames: ["that", "groupId", "ciphertext"],
      );

  @override
  Uint8List crateApiSimpleMoatSessionHandleDeviceId({
    required MoatSessionHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleDeviceIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleDeviceIdConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_device_id",
        argNames: ["that"],
      );

  @override
  Future<EncryptResultDto> crateApiSimpleMoatSessionHandleEncryptEvent({
    required MoatSessionHandle that,
    required List<int> groupId,
    required List<int> keyBundle,
    required EventDto event,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(keyBundle, serializer);
          sse_encode_box_autoadd_event_dto(event, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encrypt_result_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleEncryptEventConstMeta,
        argValues: [that, groupId, keyBundle, event],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleEncryptEventConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_encrypt_event",
        argNames: ["that", "groupId", "keyBundle", "event"],
      );

  @override
  Future<Uint8List> crateApiSimpleMoatSessionHandleExportState({
    required MoatSessionHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleExportStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleExportStateConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_export_state",
        argNames: ["that"],
      );

  @override
  Future<MoatSessionHandle> crateApiSimpleMoatSessionHandleFromState({
    required List<int> state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleFromStateConstMeta,
        argValues: [state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleFromStateConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_from_state",
        argNames: ["state"],
      );

  @override
  Future<KeyPackageResult> crateApiSimpleMoatSessionHandleGenerateKeyPackage({
    required MoatSessionHandle that,
    required String did,
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          sse_encode_String(did, serializer);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_package_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleGenerateKeyPackageConstMeta,
        argValues: [that, did, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleMoatSessionHandleGenerateKeyPackageConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_generate_key_package",
        argNames: ["that", "did", "deviceName"],
      );

  @override
  Future<List<String>> crateApiSimpleMoatSessionHandleGetGroupDids({
    required MoatSessionHandle that,
    required List<int> groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleGetGroupDidsConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleGetGroupDidsConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_get_group_dids",
        argNames: ["that", "groupId"],
      );

  @override
  Future<BigInt?> crateApiSimpleMoatSessionHandleGetGroupEpoch({
    required MoatSessionHandle that,
    required List<int> groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleGetGroupEpochConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleGetGroupEpochConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_get_group_epoch",
        argNames: ["that", "groupId"],
      );

  @override
  bool crateApiSimpleMoatSessionHandleHasPendingChanges({
    required MoatSessionHandle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleHasPendingChangesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleMoatSessionHandleHasPendingChangesConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_has_pending_changes",
        argNames: ["that"],
      );

  @override
  MoatSessionHandle crateApiSimpleMoatSessionHandleNewSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleNewSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleNewSessionConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_new_session",
        argNames: [],
      );

  @override
  Future<Uint8List> crateApiSimpleMoatSessionHandleProcessWelcome({
    required MoatSessionHandle that,
    required List<int> welcomeBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(welcomeBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMoatSessionHandleProcessWelcomeConstMeta,
        argValues: [that, welcomeBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMoatSessionHandleProcessWelcomeConstMeta =>
      const TaskConstMeta(
        debugName: "MoatSessionHandle_process_welcome",
        argNames: ["that", "welcomeBytes"],
      );

  @override
  Uint8List crateApiSimpleDeriveTag({
    required List<int> groupId,
    required BigInt epoch,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_u_64(epoch, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDeriveTagConstMeta,
        argValues: [groupId, epoch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeriveTagConstMeta => const TaskConstMeta(
    debugName: "derive_tag",
    argNames: ["groupId", "epoch"],
  );

  @override
  Future<Uint8List> crateApiSimpleEncryptForStealth({
    required List<Uint8List> recipientScanPubkeys,
    required List<int> welcomeBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(
            recipientScanPubkeys,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(welcomeBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncryptForStealthConstMeta,
        argValues: [recipientScanPubkeys, welcomeBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncryptForStealthConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_for_stealth",
        argNames: ["recipientScanPubkeys", "welcomeBytes"],
      );

  @override
  StealthKeypair crateApiSimpleGenerateStealthKeypair() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stealth_keypair,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGenerateStealthKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGenerateStealthKeypairConstMeta =>
      const TaskConstMeta(debugName: "generate_stealth_keypair", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Uint8List crateApiSimplePadToBucket({required List<int> plaintext}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePadToBucketConstMeta,
        argValues: [plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePadToBucketConstMeta =>
      const TaskConstMeta(debugName: "pad_to_bucket", argNames: ["plaintext"]);

  @override
  Uint8List? crateApiSimpleTryDecryptStealth({
    required List<int> scanPrivkey,
    required List<int> payload,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(scanPrivkey, serializer);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTryDecryptStealthConstMeta,
        argValues: [scanPrivkey, payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTryDecryptStealthConstMeta =>
      const TaskConstMeta(
        debugName: "try_decrypt_stealth",
        argNames: ["scanPrivkey", "payload"],
      );

  @override
  Uint8List crateApiSimpleUnpad({required List<int> padded}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(padded, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleUnpadConstMeta,
        argValues: [padded],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleUnpadConstMeta =>
      const TaskConstMeta(debugName: "unpad", argNames: ["padded"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MoatSessionHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MoatSessionHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle;

  @protected
  MoatSessionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MoatSessionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MoatSessionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MoatSessionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MoatSessionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MoatSessionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EventDto dco_decode_box_autoadd_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_event_dto(raw);
  }

  @protected
  SenderInfoDto dco_decode_box_autoadd_sender_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sender_info_dto(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  DecryptResultDto dco_decode_decrypt_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DecryptResultDto(
      newGroupState: dco_decode_list_prim_u_8_strict(arr[0]),
      event: dco_decode_event_dto(arr[1]),
      sender: dco_decode_opt_box_autoadd_sender_info_dto(arr[2]),
    );
  }

  @protected
  EncryptResultDto dco_decode_encrypt_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EncryptResultDto(
      newGroupState: dco_decode_list_prim_u_8_strict(arr[0]),
      tag: dco_decode_list_prim_u_8_strict(arr[1]),
      ciphertext: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  EventDto dco_decode_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EventDto(
      kind: dco_decode_event_kind_dto(arr[0]),
      groupId: dco_decode_list_prim_u_8_strict(arr[1]),
      epoch: dco_decode_u_64(arr[2]),
      payload: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  EventKindDto dco_decode_event_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EventKindDto.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  KeyPackageResult dco_decode_key_package_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyPackageResult(
      keyPackage: dco_decode_list_prim_u_8_strict(arr[0]),
      keyBundle: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SenderInfoDto? dco_decode_opt_box_autoadd_sender_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_sender_info_dto(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  SenderInfoDto dco_decode_sender_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SenderInfoDto(
      did: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
    );
  }

  @protected
  StealthKeypair dco_decode_stealth_keypair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StealthKeypair(
      privateKey: dco_decode_list_prim_u_8_strict(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WelcomeResultDto dco_decode_welcome_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WelcomeResultDto(
      newGroupState: dco_decode_list_prim_u_8_strict(arr[0]),
      welcome: dco_decode_list_prim_u_8_strict(arr[1]),
      commit: dco_decode_list_prim_u_8_strict(arr[2]),
      groupId: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  MoatSessionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MoatSessionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MoatSessionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MoatSessionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MoatSessionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MoatSessionHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EventDto sse_decode_box_autoadd_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_event_dto(deserializer));
  }

  @protected
  SenderInfoDto sse_decode_box_autoadd_sender_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sender_info_dto(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  DecryptResultDto sse_decode_decrypt_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_newGroupState = sse_decode_list_prim_u_8_strict(deserializer);
    var var_event = sse_decode_event_dto(deserializer);
    var var_sender = sse_decode_opt_box_autoadd_sender_info_dto(deserializer);
    return DecryptResultDto(
      newGroupState: var_newGroupState,
      event: var_event,
      sender: var_sender,
    );
  }

  @protected
  EncryptResultDto sse_decode_encrypt_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_newGroupState = sse_decode_list_prim_u_8_strict(deserializer);
    var var_tag = sse_decode_list_prim_u_8_strict(deserializer);
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    return EncryptResultDto(
      newGroupState: var_newGroupState,
      tag: var_tag,
      ciphertext: var_ciphertext,
    );
  }

  @protected
  EventDto sse_decode_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_event_kind_dto(deserializer);
    var var_groupId = sse_decode_list_prim_u_8_strict(deserializer);
    var var_epoch = sse_decode_u_64(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    return EventDto(
      kind: var_kind,
      groupId: var_groupId,
      epoch: var_epoch,
      payload: var_payload,
    );
  }

  @protected
  EventKindDto sse_decode_event_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EventKindDto.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  KeyPackageResult sse_decode_key_package_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyPackage = sse_decode_list_prim_u_8_strict(deserializer);
    var var_keyBundle = sse_decode_list_prim_u_8_strict(deserializer);
    return KeyPackageResult(
      keyPackage: var_keyPackage,
      keyBundle: var_keyBundle,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SenderInfoDto? sse_decode_opt_box_autoadd_sender_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_sender_info_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SenderInfoDto sse_decode_sender_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_did = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    return SenderInfoDto(did: var_did, deviceName: var_deviceName);
  }

  @protected
  StealthKeypair sse_decode_stealth_keypair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return StealthKeypair(privateKey: var_privateKey, publicKey: var_publicKey);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WelcomeResultDto sse_decode_welcome_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_newGroupState = sse_decode_list_prim_u_8_strict(deserializer);
    var var_welcome = sse_decode_list_prim_u_8_strict(deserializer);
    var var_commit = sse_decode_list_prim_u_8_strict(deserializer);
    var var_groupId = sse_decode_list_prim_u_8_strict(deserializer);
    return WelcomeResultDto(
      newGroupState: var_newGroupState,
      welcome: var_welcome,
      commit: var_commit,
      groupId: var_groupId,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    MoatSessionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MoatSessionHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    MoatSessionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MoatSessionHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoatSessionHandle(
    MoatSessionHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MoatSessionHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_event_dto(
    EventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_event_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sender_info_dto(
    SenderInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sender_info_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_decrypt_result_dto(
    DecryptResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.newGroupState, serializer);
    sse_encode_event_dto(self.event, serializer);
    sse_encode_opt_box_autoadd_sender_info_dto(self.sender, serializer);
  }

  @protected
  void sse_encode_encrypt_result_dto(
    EncryptResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.newGroupState, serializer);
    sse_encode_list_prim_u_8_strict(self.tag, serializer);
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
  }

  @protected
  void sse_encode_event_dto(EventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_event_kind_dto(self.kind, serializer);
    sse_encode_list_prim_u_8_strict(self.groupId, serializer);
    sse_encode_u_64(self.epoch, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
  }

  @protected
  void sse_encode_event_kind_dto(EventKindDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_key_package_result(
    KeyPackageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.keyPackage, serializer);
    sse_encode_list_prim_u_8_strict(self.keyBundle, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_sender_info_dto(
    SenderInfoDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_sender_info_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_sender_info_dto(
    SenderInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.did, serializer);
    sse_encode_String(self.deviceName, serializer);
  }

  @protected
  void sse_encode_stealth_keypair(
    StealthKeypair self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.privateKey, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_welcome_result_dto(
    WelcomeResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.newGroupState, serializer);
    sse_encode_list_prim_u_8_strict(self.welcome, serializer);
    sse_encode_list_prim_u_8_strict(self.commit, serializer);
    sse_encode_list_prim_u_8_strict(self.groupId, serializer);
  }
}

@sealed
class MoatSessionHandleImpl extends RustOpaque implements MoatSessionHandle {
  // Not to be used by end users
  MoatSessionHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MoatSessionHandleImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MoatSessionHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MoatSessionHandle,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_MoatSessionHandlePtr,
  );

  /// Add a member to a group. Returns welcome result.
  Future<WelcomeResultDto> addMember({
    required List<int> groupId,
    required List<int> keyBundle,
    required List<int> newMemberKeyPackage,
  }) => RustLib.instance.api.crateApiSimpleMoatSessionHandleAddMember(
    that: this,
    groupId: groupId,
    keyBundle: keyBundle,
    newMemberKeyPackage: newMemberKeyPackage,
  );

  /// Create a new MLS group with DID and device name. Returns the group ID.
  Future<Uint8List> createGroup({
    required String did,
    required String deviceName,
    required List<int> keyBundle,
  }) => RustLib.instance.api.crateApiSimpleMoatSessionHandleCreateGroup(
    that: this,
    did: did,
    deviceName: deviceName,
    keyBundle: keyBundle,
  );

  /// Decrypt a ciphertext for a group. Returns decrypt result.
  Future<DecryptResultDto> decryptEvent({
    required List<int> groupId,
    required List<int> ciphertext,
  }) => RustLib.instance.api.crateApiSimpleMoatSessionHandleDecryptEvent(
    that: this,
    groupId: groupId,
    ciphertext: ciphertext,
  );

  /// Get the 16-byte device ID.
  Uint8List deviceId() =>
      RustLib.instance.api.crateApiSimpleMoatSessionHandleDeviceId(that: this);

  /// Encrypt an event for a group. Returns encrypt result.
  Future<EncryptResultDto> encryptEvent({
    required List<int> groupId,
    required List<int> keyBundle,
    required EventDto event,
  }) => RustLib.instance.api.crateApiSimpleMoatSessionHandleEncryptEvent(
    that: this,
    groupId: groupId,
    keyBundle: keyBundle,
    event: event,
  );

  /// Export the full session state as bytes for persistence.
  Future<Uint8List> exportState() => RustLib.instance.api
      .crateApiSimpleMoatSessionHandleExportState(that: this);

  /// Generate a new key package with DID and device name.
  /// Returns (key_package_bytes, key_bundle_bytes).
  Future<KeyPackageResult> generateKeyPackage({
    required String did,
    required String deviceName,
  }) => RustLib.instance.api.crateApiSimpleMoatSessionHandleGenerateKeyPackage(
    that: this,
    did: did,
    deviceName: deviceName,
  );

  /// Get the DIDs of all members in a group (deduplicated).
  Future<List<String>> getGroupDids({required List<int> groupId}) =>
      RustLib.instance.api.crateApiSimpleMoatSessionHandleGetGroupDids(
        that: this,
        groupId: groupId,
      );

  /// Get the current epoch of a group. Returns null if group doesn't exist.
  Future<BigInt?> getGroupEpoch({required List<int> groupId}) =>
      RustLib.instance.api.crateApiSimpleMoatSessionHandleGetGroupEpoch(
        that: this,
        groupId: groupId,
      );

  /// Check if there are unsaved changes.
  bool hasPendingChanges() => RustLib.instance.api
      .crateApiSimpleMoatSessionHandleHasPendingChanges(that: this);

  /// Process a welcome message to join a group. Returns the group ID.
  Future<Uint8List> processWelcome({required List<int> welcomeBytes}) =>
      RustLib.instance.api.crateApiSimpleMoatSessionHandleProcessWelcome(
        that: this,
        welcomeBytes: welcomeBytes,
      );
}
