// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `commands_dto`, `credential_from_dto`, `device_id_from`, `from_core`, `identity_from_dto`, `into_core`, `push_media_label`, `push_plaintext_preview`, `to_core_sibling_stealth`, `token_from`, `with_env`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MoatError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`

/// Generate a stealth keypair. Returns (private_key, public_key) each 32 bytes.
StealthKeypair generateStealthKeypair() =>
    RustLib.instance.api.crateApiSimpleGenerateStealthKeypair();

/// Encrypt a Welcome for one or more recipients' stealth addresses (multi-device support).
/// Each recipient pubkey must be 32 bytes.
Future<Uint8List> encryptForStealth(
        {required List<Uint8List> recipientScanPubkeys,
        required List<int> welcomeBytes}) =>
    RustLib.instance.api.crateApiSimpleEncryptForStealth(
        recipientScanPubkeys: recipientScanPubkeys, welcomeBytes: welcomeBytes);

/// Try to decrypt a stealth-encrypted payload. Returns None if not for us.
Uint8List? tryDecryptStealth(
        {required List<int> scanPrivkey, required List<int> payload}) =>
    RustLib.instance.api.crateApiSimpleTryDecryptStealth(
        scanPrivkey: scanPrivkey, payload: payload);

/// Generate candidate tags for recipient scanning.
///
/// Returns a list of (tag, counter) pairs for the given sender in the group.
List<Uint8List> generateCandidateTags(
        {required MoatSessionHandle handle,
        required List<int> groupId,
        required String senderDid,
        required List<int> senderDeviceId,
        required BigInt fromCounter,
        required BigInt count}) =>
    RustLib.instance.api.crateApiSimpleGenerateCandidateTags(
        handle: handle,
        groupId: groupId,
        senderDid: senderDid,
        senderDeviceId: senderDeviceId,
        fromCounter: fromCounter,
        count: count);

/// Sign a Drawbridge challenge with the Ed25519 identity key from a key bundle.
///
/// Returns (signature_bytes, public_key_bytes) as raw bytes (64 and 32 bytes).
/// The caller is responsible for base64-encoding for JSON transport.
///
/// `message` is typically `"{nonce}\n{drawbridge_url}\n{timestamp}\n"`.
Future<DrawbridgeChallengeSignature> signDrawbridgeChallenge(
        {required List<int> keyBundle, required List<int> message}) =>
    RustLib.instance.api.crateApiSimpleSignDrawbridgeChallenge(
        keyBundle: keyBundle, message: message);

/// A Drawbridge URL as typed or scanned, in the form a device connects to and
/// signs: `ws://` or `wss://`, a host and a path. A bare host becomes
/// `wss://<host>/ws`. Two spellings of one Drawbridge compare equal once
/// normalised.
String normalizeDrawbridgeUrl({required String url}) =>
    RustLib.instance.api.crateApiSimpleNormalizeDrawbridgeUrl(url: url);

/// Pad plaintext to bucket size (512, 1024, or 4096 bytes).
///
/// Fails above the largest bucket: there is nothing to round up to, and
/// oversized content belongs in an external blob with only the reference
/// in the event.
Uint8List padToBucket({required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimplePadToBucket(plaintext: plaintext);

/// Remove padding and extract original plaintext.
Uint8List unpad({required List<int> padded}) =>
    RustLib.instance.api.crateApiSimpleUnpad(padded: padded);

/// Encrypt a blob. Returns encrypted bytes and metadata for ExternalBlob.
Future<BlobEncryptResult> blobEncrypt({required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimpleBlobEncrypt(plaintext: plaintext);

/// Decrypt and verify a blob.
Future<Uint8List> blobDecrypt(
        {required List<int> blob,
        required List<int> key,
        required List<int> ciphertextHash,
        required List<int> contentHash}) =>
    RustLib.instance.api.crateApiSimpleBlobDecrypt(
        blob: blob,
        key: key,
        ciphertextHash: ciphertextHash,
        contentHash: contentHash);

/// Process an image for sending: validate format, resize if >2048px, generate thumbhash.
/// Returns processed bytes, dimensions, thumbhash, and MIME type.
Future<ImageProcessResult> processImageForSend(
        {required List<int> imageBytes}) =>
    RustLib.instance.api
        .crateApiSimpleProcessImageForSend(imageBytes: imageBytes);

/// Decode a thumbhash to RGBA pixels for placeholder rendering.
Future<ThumbHashResult> decodeThumbhash({required List<int> hash}) =>
    RustLib.instance.api.crateApiSimpleDecodeThumbhash(hash: hash);

/// Decrypt a push notification payload for use in a background message handler
/// or iOS Notification Service Extension.
///
/// Reads the MLS session state from `state_path`, scans `group_ids` to find
/// which group the `tag` belongs to, decrypts `ciphertext`, advances the seen
/// counter, and writes the updated state back to `state_path` atomically
/// (write to `<state_path>.push_tmp`, then rename).
///
/// Returns `Err` if the tag is not matched in any group or if decrypt fails.
///
/// # Concurrency
/// The rename is atomic on POSIX. If the foreground app races to write state
/// simultaneously one update will win; the dedup map in moat-core makes
/// double-processing safe.
Future<DecryptedPush> decryptPushPayload(
        {required String statePath,
        required List<Uint8List> groupIds,
        required List<int> tag,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiSimpleDecryptPushPayload(
        statePath: statePath,
        groupIds: groupIds,
        tag: tag,
        ciphertext: ciphertext);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MoatSessionHandle>>
abstract class MoatSessionHandle implements RustOpaqueInterface {
  /// Add a member to a group. Returns welcome result.
  Future<WelcomeResultDto> addMember(
      {required List<int> groupId,
      required List<int> keyBundle,
      required List<int> newMemberKeyPackage});

  /// Mark a matched tag as seen and extend its sender's scanning window.
  ///
  /// Returns the newly covered tags, for the tag map and watch list.
  List<Uint8List> advanceScanWindow({required List<int> tag});

  /// Create a new MLS group with DID and device name. Returns the group ID.
  Future<Uint8List> createGroup(
      {required String did,
      required String deviceName,
      required List<int> keyBundle});

  /// Decrypt a ciphertext for a group. Returns decrypt result with any warnings.
  Future<DecryptResultDto> decryptEvent(
      {required List<int> groupId, required List<int> ciphertext});

  /// Get the 16-byte device ID.
  Uint8List deviceId();

  /// Encrypt an event for a group. Returns encrypt result.
  Future<EncryptResultDto> encryptEvent(
      {required List<int> groupId,
      required List<int> keyBundle,
      required EventDto event});

  /// The parked events, serialized for the host to persist.
  Uint8List exportParkedEvents();

  /// Export the full session state as bytes for persistence.
  Future<Uint8List> exportState();

  /// Extract the credential (DID, device_id, device_name) from a raw key package bytes.
  /// Returns None if the key package has no credential embedded.
  Future<CredentialDto?> extractCredentialFromKeyPackage(
      {required List<int> keyPackage});

  /// Restore a session from previously exported state bytes.
  static Future<MoatSessionHandle> fromState({required List<int> state}) =>
      RustLib.instance.api
          .crateApiSimpleMoatSessionHandleFromState(state: state);

  /// Generate a new key package with DID and device name.
  /// Returns (key_package_bytes, key_bundle_bytes).
  Future<KeyPackageResult> generateKeyPackage(
      {required String did, required String deviceName});

  /// Get the DIDs of all members in a group (deduplicated).
  Future<List<String>> getGroupDids({required List<int> groupId});

  /// Get the current epoch of a group. Returns null if group doesn't exist.
  Future<BigInt?> getGroupEpoch({required List<int> groupId});

  /// Return the (DID, device_id, device_name) credential for every member of a group.
  Future<List<CredentialDto>> getGroupMemberCredentials(
      {required List<int> groupId});

  /// The group a candidate tag belongs to, if it is one.
  Uint8List? groupForTag({required List<int> tag});

  /// Check if there are unsaved changes.
  bool hasPendingChanges();

  /// Restore parked events persisted with `export_parked_events`.
  int importParkedEvents({required List<int> bytes});

  /// Drop events parked too long. Returns how many were dropped.
  int inboxExpire({required PlatformInt64 nowMs});

  /// Park an event until its tag is generated.
  void inboxPark({required InboxEventDto event, required PlatformInt64 nowMs});

  /// The ready event with the lowest rkey.
  InboxEventDto? inboxPopReady();

  /// Queue a fetched event. Returns false if it is already held.
  bool inboxPush({required InboxEventDto event});

  /// Check if a DID already has a device in the group.
  bool isDidInGroup({required List<int> groupId, required String did});

  /// The device name of the member of `group_id` with `device_id`, if any.
  Future<String?> memberDeviceName(
      {required List<int> groupId, required List<int> deviceId});

  /// Create a new session with empty state.
  static MoatSessionHandle newSession() =>
      RustLib.instance.api.crateApiSimpleMoatSessionHandleNewSession();

  /// Generate all candidate tags for every member in a group.
  ///
  /// Returns a flat list of candidate tags for recipient scanning.
  List<Uint8List> populateCandidateTags({required List<int> groupId});

  /// Process a welcome message to join a group. Returns the group ID.
  Future<Uint8List> processWelcome({required List<int> welcomeBytes});

  /// Generate a fresh key package reusing the **existing** signing key from `key_bundle`.
  ///
  /// Unlike `generate_key_package`, this preserves the leaf-node public key so that
  /// all MLS groups the caller already belongs to remain usable after the call.
  /// Use this to replenish the PDS key package after a Welcome has consumed the
  /// previous one (e.g. after joining a coord group).
  ///
  /// Returns only the new key package bytes; the key bundle is unchanged.
  Future<Uint8List> replenishKeyPackage(
      {required String did,
      required String deviceName,
      required List<int> keyBundle});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PairChannelHandle>>
abstract class PairChannelHandle implements RustOpaqueInterface {
  bool isTransferring();

  static PairChannelHandle newDriver() =>
      RustLib.instance.api.crateApiSimplePairChannelHandleNewDriver();

  /// The main WS to `drawbridge_url` (re)authenticated.
  List<PairChannelCommandDto> onDrawbridgeConnected(
      {required String drawbridgeUrl});

  /// A binary frame from the pair WS for `token`.
  Future<List<PairChannelCommandDto>> onFrame(
      {required MoatSessionHandle session,
      required RingDriverHandle ring,
      required PlatformInt64 nowMs,
      required List<int> token,
      required List<int> data});

  /// The pair WS for `token` closed or failed to connect.
  List<PairChannelCommandDto> onPairClosed(
      {required List<int> token, required String reason});

  /// `pair_ready` from `drawbridge_url`.
  List<PairChannelCommandDto> onPairReady(
      {required String drawbridgeUrl,
      required List<int> token,
      required String url});

  /// The pair WS for `token` reached `paired`.
  Future<List<PairChannelCommandDto>> onPaired(
      {required MoatSessionHandle session,
      required RingDriverHandle ring,
      required PlatformInt64 nowMs,
      required List<int> token});

  /// A sibling's `ring.msg` payload. `sender_name` must come from the
  /// sender's MLS leaf credential, `sender_drawbridge_url` from the sender's
  /// `drawbridgeConfig` record.
  List<PairChannelCommandDto> onRingMsg(
      {required List<int> payload,
      required String senderName,
      required String senderDrawbridgeUrl,
      required List<int> ownDeviceId,
      required PlatformInt64 nowMs});

  List<PairChannelCommandDto> onRingPublishFailed(
      {required List<int> tag, required String detail});

  /// Existing device: approve the pending `Enroll`. A failure while
  /// approving fails the pairing rather than returning `Err`.
  Future<List<PairChannelCommandDto>> pairApprove(
      {required MoatSessionHandle session,
      required RingDriverHandle ring,
      required PlatformInt64 nowMs,
      required List<SiblingStealthDto> siblingStealth});

  List<PairChannelCommandDto> pairCancel();

  /// Existing device: enter a code, in its text or `moat-pair:` form, with
  /// the Drawbridge shown beside it (a `moat-pair:` URI names its own).
  List<PairChannelCommandDto> pairConfirm(
      {required PairIdentityDto identity,
      required String code,
      String? drawbridgeUrl});

  /// New device: start a pairing on `drawbridge_url`, this device's Drawbridge; the code
  /// is what the screen shows, beside the Drawbridge.
  PairNewDto pairNew(
      {required PairIdentityDto identity, required String drawbridgeUrl});

  List<PairChannelCommandDto> pairReject();

  PairingUiStateDto pairingUiState();

  SyncProgressDto? progress();

  Future<List<PairChannelCommandDto>> provideHistory(
      {required MoatSessionHandle session,
      required RingDriverHandle ring,
      required PlatformInt64 nowMs,
      required List<int> token,
      required List<ConvHistoryDto> history});

  /// The Drawbridge the live rendezvous is on, if there is one.
  String? rendezvousDrawbridgeUrl();

  List<PairChannelCommandDto> syncAccept();

  void syncDecline();

  /// Offer this device's history to `target`.
  Future<List<PairChannelCommandDto>> syncOffer(
      {required MoatSessionHandle session,
      required RingDriverHandle ring,
      required PlatformInt64 nowMs,
      required List<int> keyBundle,
      required List<int> target,
      required String drawbridgeUrl});

  /// Ask the user's other devices for history; `target` names one.
  /// `key_bundle` seals the request to the ring; `drawbridge_url` is this device's
  /// Drawbridge, where the rendezvous happens.
  Future<List<PairChannelCommandDto>> syncRequest(
      {required MoatSessionHandle session,
      required RingDriverHandle ring,
      required PlatformInt64 nowMs,
      required List<int> keyBundle,
      Uint8List? target,
      required String drawbridgeUrl});

  SyncRequestUiStateDto syncRequestUiState();

  /// Expire an unanswered sync request.
  List<PairChannelCommandDto> tick({required PlatformInt64 nowMs});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RingDriverHandle>>
abstract class RingDriverHandle implements RustOpaqueInterface {
  /// Claim one unused key package from the local pool for `owner`, marking
  /// its seq consumed.  `None` means the pool is drained — the host should
  /// emit a `KpRequest` via [`Self::emit_kp_request_for`] and defer the add
  /// until a `KpBatch` arrives.  Single-use enforcement lives here, not in
  /// the host: a seq is never returned twice, even if replayed into the
  /// pool.
  OfferedKpDto? claimKp({required List<int> ownerDeviceId});

  /// One-line snapshot of ring membership and peer states, for the Dart
  /// host's debug log. Same renderer as `moat-cli` uses, so a mixed-runtime
  /// beacon failure produces comparable lines from both sides.
  String debugSummary();

  /// Emit a `KpRequest` to `owner` asking it to top up our pool.  The host
  /// publishes the returned commands.  Empty if not in a ring or if the
  /// sibling's stealth record is not yet known (self-healing: the next poll
  /// retries).
  Future<List<RingCommandDto>> emitKpRequestFor(
      {required MoatSessionHandle session,
      required String myDid,
      required List<int> keyBundle,
      required List<SiblingStealthDto> siblingStealth,
      required List<int> ownerDeviceId});

  /// Build the stealth-publish command carrying a `CoordMsg::UserConvWelcome`
  /// for `owner`.  The CoordMsg framing stays in Rust so the wire format has
  /// a single owner.  `None` if not in a ring or the sibling's stealth
  /// record is unknown.
  ///
  /// Flat parameter list rather than a bundled struct: each `#[frb]`
  /// parameter becomes a named argument in the generated Dart binding, so
  /// callers get the same readability a struct would give without an
  /// extra DTO to keep in sync.
  Future<RingCommandDto?> encryptUserConvWelcome(
      {required MoatSessionHandle session,
      required String myDid,
      required List<int> keyBundle,
      required List<SiblingStealthDto> siblingStealth,
      required List<int> ownerDeviceId,
      required List<int> groupId,
      required List<int> welcome});

  /// Restore a ring state from its persisted JSON.
  static Future<RingDriverHandle> fromStateJson({required String json}) =>
      RustLib.instance.api
          .crateApiSimpleRingDriverHandleFromStateJson(json: json);

  /// Create a new ring state with empty state.
  static RingDriverHandle newEmpty() =>
      RustLib.instance.api.crateApiSimpleRingDriverHandleNewEmpty();

  /// Cursor (rkey) for incremental own-PDS stealth scan.
  String? ownEventsCursor();

  /// Record that we are now an MLS member of `ring_id`, looking up our
  /// own leaf index from the group's member list. Called once, host-side,
  /// when a pairing exchange completes — the new device from
  /// `PairingCommandDto.persistRing`, the existing device right after a
  /// successful `PairingSessionHandle.approve` (which has no command of
  /// its own for this, since it already knows it just created/joined
  /// `ring_id`). Mirrors `moat-cli`'s `App`-level interpreter.
  Future<void> recordRingMembership(
      {required MoatSessionHandle session,
      required List<int> ringId,
      required PlatformInt64 nowMs});

  /// Raw ring group ID, if a ring exists.
  Uint8List? ringGroupId();

  /// Device ids of siblings confirmed to be in the ring.  Drives the
  /// same-user fan-out loop in the host.
  List<Uint8List> ringJoinedSiblings({required MoatSessionHandle session});

  /// Drive one ring coordination tick. Returns commands for the host to interpret.
  Future<List<RingCommandDto>> tick(
      {required MoatSessionHandle session, required TickInputsDto inputs});

  /// Serialise the current ring state as JSON.
  Future<String> toStateJson();
}

class BlobEncryptResult {
  /// Encrypted bytes: nonce (24 bytes) || ciphertext.
  final Uint8List blob;

  /// 32-byte symmetric key.
  final Uint8List key;

  /// SHA-256 of blob (pre-decryption integrity check).
  final Uint8List ciphertextHash;

  /// SHA-256 of plaintext (post-decryption integrity check and cache key).
  final Uint8List contentHash;

  const BlobEncryptResult({
    required this.blob,
    required this.key,
    required this.ciphertextHash,
    required this.contentHash,
  });

  @override
  int get hashCode =>
      blob.hashCode ^
      key.hashCode ^
      ciphertextHash.hashCode ^
      contentHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlobEncryptResult &&
          runtimeType == other.runtimeType &&
          blob == other.blob &&
          key == other.key &&
          ciphertextHash == other.ciphertextHash &&
          contentHash == other.contentHash;
}

/// One conversation's settled messages, for a transfer's `Hello`.
class ConvHistoryDto {
  final Uint8List groupId;
  final List<SyncMessageDto> messages;

  const ConvHistoryDto({
    required this.groupId,
    required this.messages,
  });

  @override
  int get hashCode => groupId.hashCode ^ messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvHistoryDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          messages == other.messages;
}

/// Credential fields for a group member or key package.
class CredentialDto {
  final String did;
  final Uint8List deviceId;
  final String deviceName;

  const CredentialDto({
    required this.did,
    required this.deviceId,
    required this.deviceName,
  });

  @override
  int get hashCode => did.hashCode ^ deviceId.hashCode ^ deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CredentialDto &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName;
}

class DecryptResultDto {
  final Uint8List newGroupState;
  final EventDto event;
  final SenderInfoDto? sender;

  /// Transcript integrity warnings (empty if none).
  final List<String> warnings;

  const DecryptResultDto({
    required this.newGroupState,
    required this.event,
    this.sender,
    required this.warnings,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      event.hashCode ^
      sender.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          event == other.event &&
          sender == other.sender &&
          warnings == other.warnings;
}

/// Result of decrypting a push notification payload.
class DecryptedPush {
  /// DID of the message sender, extracted from their MLS credential.
  final String? senderDid;

  /// Human-readable preview for the notification body (truncated to 200 chars).
  /// `None` for protocol messages (commit, welcome, checkpoint) that should not
  /// generate a visible notification.
  final String? plaintextPreview;

  /// The MLS group ID the message belongs to.
  final Uint8List groupId;

  /// 16-byte message ID for deduplication (present for Message and Reaction events).
  final Uint8List? messageId;

  const DecryptedPush({
    this.senderDid,
    this.plaintextPreview,
    required this.groupId,
    this.messageId,
  });

  @override
  int get hashCode =>
      senderDid.hashCode ^
      plaintextPreview.hashCode ^
      groupId.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedPush &&
          runtimeType == other.runtimeType &&
          senderDid == other.senderDid &&
          plaintextPreview == other.plaintextPreview &&
          groupId == other.groupId &&
          messageId == other.messageId;
}

/// Result of signing a Drawbridge challenge.
class DrawbridgeChallengeSignature {
  /// Ed25519 signature (64 bytes)
  final Uint8List signature;

  /// Ed25519 public key (32 bytes)
  final Uint8List publicKey;

  const DrawbridgeChallengeSignature({
    required this.signature,
    required this.publicKey,
  });

  @override
  int get hashCode => signature.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawbridgeChallengeSignature &&
          runtimeType == other.runtimeType &&
          signature == other.signature &&
          publicKey == other.publicKey;
}

class EncryptResultDto {
  final Uint8List newGroupState;
  final Uint8List tag;
  final Uint8List ciphertext;
  final Uint8List? messageId;

  const EncryptResultDto({
    required this.newGroupState,
    required this.tag,
    required this.ciphertext,
    this.messageId,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      tag.hashCode ^
      ciphertext.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          tag == other.tag &&
          ciphertext == other.ciphertext &&
          messageId == other.messageId;
}

class EventDto {
  final EventKindDto kind;
  final Uint8List groupId;
  final BigInt epoch;
  final Uint8List payload;

  /// Unique message identifier (16 random bytes). Present for Message and Reaction events.
  final Uint8List? messageId;

  const EventDto({
    required this.kind,
    required this.groupId,
    required this.epoch,
    required this.payload,
    this.messageId,
  });

  /// Parse the payload as a reaction. Only valid when kind is Reaction.
  /// Returns None if this is not a Reaction event or if the payload is malformed.
  ReactionPayloadDto? reactionPayload() =>
      RustLib.instance.api.crateApiSimpleEventDtoReactionPayload(
        that: this,
      );

  @override
  int get hashCode =>
      kind.hashCode ^
      groupId.hashCode ^
      epoch.hashCode ^
      payload.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          groupId == other.groupId &&
          epoch == other.epoch &&
          payload == other.payload &&
          messageId == other.messageId;
}

enum EventKindDto {
  message,
  commit,
  welcome,
  checkpoint,
  reaction,
  ringMsg,
  unknown,
  ;
}

enum GroupKindDto {
  user,
  ring,
  ;
}

class ImageProcessResult {
  /// Processed image bytes (JPEG or PNG, resized if >2048px).
  final Uint8List imageBytes;
  final int width;
  final int height;

  /// ThumbHash bytes for blurry placeholder preview.
  final Uint8List thumbhash;

  /// MIME type: "image/jpeg" or "image/png".
  final String mimeType;

  const ImageProcessResult({
    required this.imageBytes,
    required this.width,
    required this.height,
    required this.thumbhash,
    required this.mimeType,
  });

  @override
  int get hashCode =>
      imageBytes.hashCode ^
      width.hashCode ^
      height.hashCode ^
      thumbhash.hashCode ^
      mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageProcessResult &&
          runtimeType == other.runtimeType &&
          imageBytes == other.imageBytes &&
          width == other.width &&
          height == other.height &&
          thumbhash == other.thumbhash &&
          mimeType == other.mimeType;
}

/// A fetched `social.moat.event` record, as the inbox holds it.
class InboxEventDto {
  /// The DID whose PDS the record was fetched from.
  final String sourceDid;
  final String rkey;
  final String authorDid;
  final Uint8List tag;
  final Uint8List ciphertext;
  final PlatformInt64 createdAtMs;

  const InboxEventDto({
    required this.sourceDid,
    required this.rkey,
    required this.authorDid,
    required this.tag,
    required this.ciphertext,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      sourceDid.hashCode ^
      rkey.hashCode ^
      authorDid.hashCode ^
      tag.hashCode ^
      ciphertext.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboxEventDto &&
          runtimeType == other.runtimeType &&
          sourceDid == other.sourceDid &&
          rkey == other.rkey &&
          authorDid == other.authorDid &&
          tag == other.tag &&
          ciphertext == other.ciphertext &&
          createdAtMs == other.createdAtMs;
}

class KeyPackageResult {
  final Uint8List keyPackage;
  final Uint8List keyBundle;

  const KeyPackageResult({
    required this.keyPackage,
    required this.keyBundle,
  });

  @override
  int get hashCode => keyPackage.hashCode ^ keyBundle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageResult &&
          runtimeType == other.runtimeType &&
          keyPackage == other.keyPackage &&
          keyBundle == other.keyBundle;
}

/// One key package drawn from the same-user KP pool.
class OfferedKpDto {
  final Uint8List rkey;
  final BigInt seq;
  final Uint8List keyPackage;

  const OfferedKpDto({
    required this.rkey,
    required this.seq,
    required this.keyPackage,
  });

  @override
  int get hashCode => rkey.hashCode ^ seq.hashCode ^ keyPackage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OfferedKpDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          seq == other.seq &&
          keyPackage == other.keyPackage;
}

class OwnEventInputDto {
  final String rkey;
  final Uint8List ciphertext;

  const OwnEventInputDto({
    required this.rkey,
    required this.ciphertext,
  });

  @override
  int get hashCode => rkey.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OwnEventInputDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          ciphertext == other.ciphertext;
}

@freezed
sealed class PairChannelCommandDto with _$PairChannelCommandDto {
  const PairChannelCommandDto._();

  /// Send `pair_offer` on an authenticated main WS to `drawbridge_url`.
  const factory PairChannelCommandDto.sendPairOffer({
    required String drawbridgeUrl,
    required Uint8List token,
  }) = PairChannelCommandDto_SendPairOffer;

  /// Send `pair_join` on an authenticated main WS to `drawbridge_url`.
  const factory PairChannelCommandDto.sendPairJoin({
    required String drawbridgeUrl,
    required Uint8List token,
  }) = PairChannelCommandDto_SendPairJoin;
  const factory PairChannelCommandDto.connectPair({
    required String url,
    required Uint8List token,
  }) = PairChannelCommandDto_ConnectPair;
  const factory PairChannelCommandDto.sendFrame({
    required Uint8List data,
  }) = PairChannelCommandDto_SendFrame;

  /// Close the pair WS behind the frames already sent.
  const factory PairChannelCommandDto.closePair() =
      PairChannelCommandDto_ClosePair;

  /// Tear the pair WS down now, and stop resending any unacknowledged
  /// offer or join.
  const factory PairChannelCommandDto.dropPair() =
      PairChannelCommandDto_DropPair;

  /// Publish to this device's repo and tell the relay; report a failure
  /// through `on_ring_publish_failed`.
  const factory PairChannelCommandDto.publishRingEvent({
    required Uint8List tag,
    required Uint8List ciphertext,
  }) = PairChannelCommandDto_PublishRingEvent;

  /// Load every conversation's settled history and hand it to
  /// `provide_history` with this token.
  const factory PairChannelCommandDto.loadHistory({
    required Uint8List token,
  }) = PairChannelCommandDto_LoadHistory;
  const factory PairChannelCommandDto.storeMessages({
    required String convId,
    required List<SyncMessageDto> messages,
  }) = PairChannelCommandDto_StoreMessages;
  const factory PairChannelCommandDto.saveMlsState() =
      PairChannelCommandDto_SaveMlsState;
  const factory PairChannelCommandDto.saveRingState() =
      PairChannelCommandDto_SaveRingState;
  const factory PairChannelCommandDto.ringJoined({
    required Uint8List ringId,
  }) = PairChannelCommandDto_RingJoined;
  const factory PairChannelCommandDto.deviceAdmitted({
    required Uint8List ringId,
  }) = PairChannelCommandDto_DeviceAdmitted;
  const factory PairChannelCommandDto.siblingStealthLearned({
    required Uint8List deviceId,
    required Uint8List scanPubkey,
  }) = PairChannelCommandDto_SiblingStealthLearned;
  const factory PairChannelCommandDto.transferComplete({
    required SyncTallyDto tally,
  }) = PairChannelCommandDto_TransferComplete;
  const factory PairChannelCommandDto.transferFailed({
    required String detail,
    required bool duringPairing,
  }) = PairChannelCommandDto_TransferFailed;
  const factory PairChannelCommandDto.log({
    required String line,
  }) = PairChannelCommandDto_Log;
}

/// This device's identity, which a pairing keeps for its steps.
class PairIdentityDto {
  final CredentialDto credential;
  final Uint8List keyBundle;

  /// 32-byte X25519 stealth scan public key.
  final Uint8List stealthPubkey;

  const PairIdentityDto({
    required this.credential,
    required this.keyBundle,
    required this.stealthPubkey,
  });

  @override
  int get hashCode =>
      credential.hashCode ^ keyBundle.hashCode ^ stealthPubkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairIdentityDto &&
          runtimeType == other.runtimeType &&
          credential == other.credential &&
          keyBundle == other.keyBundle &&
          stealthPubkey == other.stealthPubkey;
}

/// `pair_new`'s code, and the commands that start its rendezvous.
class PairNewDto {
  final String code;
  final List<PairChannelCommandDto> commands;

  const PairNewDto({
    required this.code,
    required this.commands,
  });

  @override
  int get hashCode => code.hashCode ^ commands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairNewDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          commands == other.commands;
}

@freezed
sealed class PairingUiStateDto with _$PairingUiStateDto {
  const PairingUiStateDto._();

  /// No pairing in flight.
  const factory PairingUiStateDto.idle() = PairingUiStateDto_Idle;

  /// New device: code generated, waiting for the peer to enter it.
  const factory PairingUiStateDto.showingCode({
    required String code,
    required String drawbridgeUrl,
    required String uri,
  }) = PairingUiStateDto_ShowingCode;

  /// Existing device: code accepted, waiting for the peer's `Enroll`.
  const factory PairingUiStateDto.awaitingPeer() =
      PairingUiStateDto_AwaitingPeer;

  /// Existing device: `Enroll` received, waiting on the approve/reject
  /// decision.
  const factory PairingUiStateDto.awaitingApproval({
    required String deviceName,
    required String did,
  }) = PairingUiStateDto_AwaitingApproval;

  /// Enroll/Admit exchange complete. Says nothing about history sync —
  /// that stays observable via `syncStatus`.
  const factory PairingUiStateDto.done({
    required Uint8List ringId,
  }) = PairingUiStateDto_Done;

  /// Terminal failure, with a reason retained on the session rather than
  /// thrown away.
  const factory PairingUiStateDto.failed({
    required String reason,
  }) = PairingUiStateDto_Failed;
}

/// Reaction payload extracted from a Reaction event.
class ReactionPayloadDto {
  final String emoji;
  final Uint8List targetMessageId;

  const ReactionPayloadDto({
    required this.emoji,
    required this.targetMessageId,
  });

  @override
  int get hashCode => emoji.hashCode ^ targetMessageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReactionPayloadDto &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          targetMessageId == other.targetMessageId;
}

@freezed
sealed class RingCommandDto with _$RingCommandDto {
  const RingCommandDto._();

  const factory RingCommandDto.publishStealthEvent({
    required Uint8List tag,
    required Uint8List ciphertext,
  }) = RingCommandDto_PublishStealthEvent;
  const factory RingCommandDto.replenishKeyPackage() =
      RingCommandDto_ReplenishKeyPackage;
  const factory RingCommandDto.registerGroup({
    required Uint8List groupId,
    required GroupKindDto kind,
  }) = RingCommandDto_RegisterGroup;
  const factory RingCommandDto.pollForNewDevices() =
      RingCommandDto_PollForNewDevices;
}

/// Information about the sender of a message, extracted from MLS credentials.
class SenderInfoDto {
  final String did;

  /// The sender's device name (format: "did:plc:xxx/Device Name")
  final String deviceName;

  /// The sender's stable 16-byte device id, from their MLS credential.
  final Uint8List deviceId;

  const SenderInfoDto({
    required this.did,
    required this.deviceName,
    required this.deviceId,
  });

  @override
  int get hashCode => did.hashCode ^ deviceName.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenderInfoDto &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          deviceName == other.deviceName &&
          deviceId == other.deviceId;
}

/// A sibling device's stealth address: the 32-byte X25519 scan pubkey plus the
/// stable 16-byte device id it belongs to.  Mirrors `moat_core::SiblingStealth`.
class SiblingStealthDto {
  final Uint8List scanPubkey;
  final Uint8List deviceId;

  const SiblingStealthDto({
    required this.scanPubkey,
    required this.deviceId,
  });

  @override
  int get hashCode => scanPubkey.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SiblingStealthDto &&
          runtimeType == other.runtimeType &&
          scanPubkey == other.scanPubkey &&
          deviceId == other.deviceId;
}

class StealthKeypair {
  final Uint8List privateKey;
  final Uint8List publicKey;

  const StealthKeypair({
    required this.privateKey,
    required this.publicKey,
  });

  @override
  int get hashCode => privateKey.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StealthKeypair &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey &&
          publicKey == other.publicKey;
}

@freezed
sealed class SyncFailureDto with _$SyncFailureDto {
  const SyncFailureDto._();

  /// Requester: nobody joined the rendezvous before it expired.
  const factory SyncFailureDto.noAnswer() = SyncFailureDto_NoAnswer;

  /// Responder: the request expired before this device answered it.
  const factory SyncFailureDto.requestExpired() = SyncFailureDto_RequestExpired;

  /// This device's user declined a sibling's request.
  const factory SyncFailureDto.declined() = SyncFailureDto_Declined;

  /// The pair channel closed before the transfer finished.
  const factory SyncFailureDto.channelClosed({
    required String detail,
  }) = SyncFailureDto_ChannelClosed;

  /// The request could not be published to the ring at all.
  const factory SyncFailureDto.publishFailed({
    required String detail,
  }) = SyncFailureDto_PublishFailed;
}

class SyncMessageDto {
  final String rkey;
  final Uint8List? messageId;
  final String senderDid;
  final String senderDeviceName;
  final PlatformInt64 timestampMs;
  final String content;
  final String? blobUri;
  final Uint8List? blobKey;
  final Uint8List? blobCiphertextHash;
  final BigInt? blobCiphertextSize;
  final Uint8List? blobContentHash;
  final String? blobMime;
  final int? blobWidth;
  final int? blobHeight;

  /// The image's blurry placeholder, shown while the blob downloads.
  final Uint8List? blobThumbhash;

  /// Emoji reactions on this message. Carried because the receiving
  /// device cannot rebuild them: reaction events predating its
  /// membership are not decryptable to it.
  final List<SyncReactionDto> reactions;

  const SyncMessageDto({
    required this.rkey,
    this.messageId,
    required this.senderDid,
    required this.senderDeviceName,
    required this.timestampMs,
    required this.content,
    this.blobUri,
    this.blobKey,
    this.blobCiphertextHash,
    this.blobCiphertextSize,
    this.blobContentHash,
    this.blobMime,
    this.blobWidth,
    this.blobHeight,
    this.blobThumbhash,
    required this.reactions,
  });

  @override
  int get hashCode =>
      rkey.hashCode ^
      messageId.hashCode ^
      senderDid.hashCode ^
      senderDeviceName.hashCode ^
      timestampMs.hashCode ^
      content.hashCode ^
      blobUri.hashCode ^
      blobKey.hashCode ^
      blobCiphertextHash.hashCode ^
      blobCiphertextSize.hashCode ^
      blobContentHash.hashCode ^
      blobMime.hashCode ^
      blobWidth.hashCode ^
      blobHeight.hashCode ^
      blobThumbhash.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncMessageDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          messageId == other.messageId &&
          senderDid == other.senderDid &&
          senderDeviceName == other.senderDeviceName &&
          timestampMs == other.timestampMs &&
          content == other.content &&
          blobUri == other.blobUri &&
          blobKey == other.blobKey &&
          blobCiphertextHash == other.blobCiphertextHash &&
          blobCiphertextSize == other.blobCiphertextSize &&
          blobContentHash == other.blobContentHash &&
          blobMime == other.blobMime &&
          blobWidth == other.blobWidth &&
          blobHeight == other.blobHeight &&
          blobThumbhash == other.blobThumbhash &&
          reactions == other.reactions;
}

@freezed
sealed class SyncProgressDto with _$SyncProgressDto {
  const SyncProgressDto._();

  const factory SyncProgressDto.starting() = SyncProgressDto_Starting;
  const factory SyncProgressDto.transferring({
    required BigInt received,
    required BigInt receiveTotal,
    required BigInt sent,
    required BigInt sendTotal,
    required double fraction,
  }) = SyncProgressDto_Transferring;
}

/// One emoji reaction, as carried by a synced message.
class SyncReactionDto {
  final String emoji;
  final String senderDid;

  const SyncReactionDto({
    required this.emoji,
    required this.senderDid,
  });

  @override
  int get hashCode => emoji.hashCode ^ senderDid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncReactionDto &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          senderDid == other.senderDid;
}

@freezed
sealed class SyncRequestUiStateDto with _$SyncRequestUiStateDto {
  const SyncRequestUiStateDto._();

  /// No sync request in flight.
  const factory SyncRequestUiStateDto.idle() = SyncRequestUiStateDto_Idle;

  /// Waiting on the rendezvous, in either role.
  const factory SyncRequestUiStateDto.awaitingPeer() =
      SyncRequestUiStateDto_AwaitingPeer;

  /// A sibling asked for history; this device's user has not decided.
  const factory SyncRequestUiStateDto.awaitingApproval({
    required String deviceName,
  }) = SyncRequestUiStateDto_AwaitingApproval;

  /// Channel up, transfer running.
  const factory SyncRequestUiStateDto.active() = SyncRequestUiStateDto_Active;

  /// Transfer finished, with what it moved and where from.
  const factory SyncRequestUiStateDto.complete({
    required SyncTallyDto tally,
    String? deviceName,
  }) = SyncRequestUiStateDto_Complete;

  /// Terminal failure, with the structured reason retained.
  const factory SyncRequestUiStateDto.failed({
    required SyncFailureDto reason,
  }) = SyncRequestUiStateDto_Failed;
}

/// What a finished sync moved in each direction. See `moat_core::SyncTally`.
class SyncTallyDto {
  final BigInt messages;
  final BigInt conversations;
  final BigInt sentMessages;
  final BigInt sentConversations;

  const SyncTallyDto({
    required this.messages,
    required this.conversations,
    required this.sentMessages,
    required this.sentConversations,
  });

  static Future<SyncTallyDto> default_() =>
      RustLib.instance.api.crateApiSimpleSyncTallyDtoDefault();

  @override
  int get hashCode =>
      messages.hashCode ^
      conversations.hashCode ^
      sentMessages.hashCode ^
      sentConversations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncTallyDto &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          conversations == other.conversations &&
          sentMessages == other.sentMessages &&
          sentConversations == other.sentConversations;
}

class ThumbHashResult {
  /// Raw RGBA pixel data (width * height * 4 bytes).
  final Uint8List rgba;
  final int width;
  final int height;

  const ThumbHashResult({
    required this.rgba,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => rgba.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbHashResult &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba &&
          width == other.width &&
          height == other.height;
}

class TickInputsDto {
  /// Sibling key packages fetched from our own PDS (driver filters out our own).
  final List<Uint8List> keyPackages;

  /// Per-sibling stealth addressing: `scan_pubkey` paired with the stable
  /// `device_id` it belongs to.  Required for the ring driver to address
  /// steady-state `SiblingMsg` payloads at a specific sibling.  Callers
  /// should filter out their own device.
  final List<SiblingStealthDto> siblingStealth;

  /// Own-PDS events since `own_events_cursor`.
  final List<OwnEventInputDto> ownEvents;

  /// Our stealth scan private key (32 bytes).
  final Uint8List stealthPrivkey;

  /// Our DID.
  final String did;

  /// Our device name.
  final String deviceName;

  /// Identity key bundle.
  final Uint8List keyBundle;

  /// Wall-clock time (ms since epoch); used as `ring_created_at` for new rings.
  final PlatformInt64 nowMs;

  const TickInputsDto({
    required this.keyPackages,
    required this.siblingStealth,
    required this.ownEvents,
    required this.stealthPrivkey,
    required this.did,
    required this.deviceName,
    required this.keyBundle,
    required this.nowMs,
  });

  @override
  int get hashCode =>
      keyPackages.hashCode ^
      siblingStealth.hashCode ^
      ownEvents.hashCode ^
      stealthPrivkey.hashCode ^
      did.hashCode ^
      deviceName.hashCode ^
      keyBundle.hashCode ^
      nowMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TickInputsDto &&
          runtimeType == other.runtimeType &&
          keyPackages == other.keyPackages &&
          siblingStealth == other.siblingStealth &&
          ownEvents == other.ownEvents &&
          stealthPrivkey == other.stealthPrivkey &&
          did == other.did &&
          deviceName == other.deviceName &&
          keyBundle == other.keyBundle &&
          nowMs == other.nowMs;
}

class WelcomeResultDto {
  final Uint8List newGroupState;
  final Uint8List welcome;
  final Uint8List commit;
  final Uint8List commitTag;
  final Uint8List groupId;

  const WelcomeResultDto({
    required this.newGroupState,
    required this.welcome,
    required this.commit,
    required this.commitTag,
    required this.groupId,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      welcome.hashCode ^
      commit.hashCode ^
      commitTag.hashCode ^
      groupId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WelcomeResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          welcome == other.welcome &&
          commit == other.commit &&
          commitTag == other.commitTag &&
          groupId == other.groupId;
}
