// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `into_core`, `push_media_label`, `push_plaintext_preview`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MoatError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Generate a stealth keypair. Returns (private_key, public_key) each 32 bytes.
StealthKeypair generateStealthKeypair() =>
    RustLib.instance.api.crateApiSimpleGenerateStealthKeypair();

/// Encrypt a Welcome for one or more recipients' stealth addresses (multi-device support).
/// Each recipient pubkey must be 32 bytes.
Future<Uint8List> encryptForStealth(
        {required List<Uint8List> recipientScanPubkeys,
        required List<int> welcomeBytes}) =>
    RustLib.instance.api.crateApiSimpleEncryptForStealth(
        recipientScanPubkeys: recipientScanPubkeys, welcomeBytes: welcomeBytes);

/// Try to decrypt a stealth-encrypted payload. Returns None if not for us.
Uint8List? tryDecryptStealth(
        {required List<int> scanPrivkey, required List<int> payload}) =>
    RustLib.instance.api.crateApiSimpleTryDecryptStealth(
        scanPrivkey: scanPrivkey, payload: payload);

/// Generate candidate tags for recipient scanning.
///
/// Returns a list of (tag, counter) pairs for the given sender in the group.
List<Uint8List> generateCandidateTags(
        {required MoatSessionHandle handle,
        required List<int> groupId,
        required String senderDid,
        required List<int> senderDeviceId,
        required BigInt fromCounter,
        required BigInt count}) =>
    RustLib.instance.api.crateApiSimpleGenerateCandidateTags(
        handle: handle,
        groupId: groupId,
        senderDid: senderDid,
        senderDeviceId: senderDeviceId,
        fromCounter: fromCounter,
        count: count);

/// Derive the next unique tag for publishing an event (increments counter).
Uint8List deriveNextTag(
        {required MoatSessionHandle handle,
        required List<int> groupId,
        required List<int> keyBundle}) =>
    RustLib.instance.api.crateApiSimpleDeriveNextTag(
        handle: handle, groupId: groupId, keyBundle: keyBundle);

/// Sign a Drawbridge challenge with the Ed25519 identity key from a key bundle.
///
/// Returns (signature_bytes, public_key_bytes) as raw bytes (64 and 32 bytes).
/// The caller is responsible for base64-encoding for JSON transport.
///
/// `message` is typically `"{nonce}\n{relay_url}\n{timestamp}\n"`.
Future<DrawbridgeChallengeSignature> signDrawbridgeChallenge(
        {required List<int> keyBundle, required List<int> message}) =>
    RustLib.instance.api.crateApiSimpleSignDrawbridgeChallenge(
        keyBundle: keyBundle, message: message);

/// Pad plaintext to bucket size (256, 1024, or 4096 bytes).
Uint8List padToBucket({required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimplePadToBucket(plaintext: plaintext);

/// Remove padding and extract original plaintext.
Uint8List unpad({required List<int> padded}) =>
    RustLib.instance.api.crateApiSimpleUnpad(padded: padded);

/// Encrypt a blob. Returns encrypted bytes and metadata for ExternalBlob.
Future<BlobEncryptResult> blobEncrypt({required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimpleBlobEncrypt(plaintext: plaintext);

/// Decrypt and verify a blob.
Future<Uint8List> blobDecrypt(
        {required List<int> blob,
        required List<int> key,
        required List<int> ciphertextHash,
        required List<int> contentHash}) =>
    RustLib.instance.api.crateApiSimpleBlobDecrypt(
        blob: blob,
        key: key,
        ciphertextHash: ciphertextHash,
        contentHash: contentHash);

/// Process an image for sending: validate format, resize if >2048px, generate thumbhash.
/// Returns processed bytes, dimensions, thumbhash, and MIME type.
Future<ImageProcessResult> processImageForSend(
        {required List<int> imageBytes}) =>
    RustLib.instance.api
        .crateApiSimpleProcessImageForSend(imageBytes: imageBytes);

/// Decode a thumbhash to RGBA pixels for placeholder rendering.
Future<ThumbHashResult> decodeThumbhash({required List<int> hash}) =>
    RustLib.instance.api.crateApiSimpleDecodeThumbhash(hash: hash);

/// Decrypt a push notification payload for use in a background message handler
/// or iOS Notification Service Extension.
///
/// Reads the MLS session state from `state_path`, scans `group_ids` to find
/// which group the `tag` belongs to, decrypts `ciphertext`, advances the seen
/// counter, and writes the updated state back to `state_path` atomically
/// (write to `<state_path>.push_tmp`, then rename).
///
/// Returns `Err` if the tag is not matched in any group or if decrypt fails.
///
/// # Concurrency
/// The rename is atomic on POSIX. If the foreground app races to write state
/// simultaneously one update will win; the dedup map in moat-core makes
/// double-processing safe.
Future<DecryptedPush> decryptPushPayload(
        {required String statePath,
        required List<Uint8List> groupIds,
        required List<int> tag,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiSimpleDecryptPushPayload(
        statePath: statePath,
        groupIds: groupIds,
        tag: tag,
        ciphertext: ciphertext);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MoatSessionHandle>>
abstract class MoatSessionHandle implements RustOpaqueInterface {
  /// Add a member to a group. Returns welcome result.
  Future<WelcomeResultDto> addMember(
      {required List<int> groupId,
      required List<int> keyBundle,
      required List<int> newMemberKeyPackage});

  /// Create a new MLS group with DID and device name. Returns the group ID.
  Future<Uint8List> createGroup(
      {required String did,
      required String deviceName,
      required List<int> keyBundle});

  /// Decrypt a ciphertext for a group. Returns decrypt result with any warnings.
  Future<DecryptResultDto> decryptEvent(
      {required List<int> groupId, required List<int> ciphertext});

  /// Decrypt an incoming `/pair` WS binary frame as a `SyncApp` event in the
  /// ring group. Returns the inner payload bytes (`SyncMsg` JSON) on success,
  /// or an error if decrypt failed or the event was not a `SyncApp`.
  Future<Uint8List> decryptSyncFrame(
      {required List<int> ringGroupId, required List<int> ciphertext});

  /// Get the 16-byte device ID.
  Uint8List deviceId();

  /// Sparse digest anchors for a group, oldest-first.
  Future<List<SyncAnchorDto>> digestAnchors({required List<int> groupId});

  /// Oldest and newest known rkeys for a group, or None if the transcript is empty.
  Future<(String, String)?> digestRange({required List<int> groupId});

  /// Tip digest for a group. None if the group doesn't exist or has no transcript yet.
  Future<Uint8List?> digestTip({required List<int> groupId});

  /// Encrypt an event for a group. Returns encrypt result.
  Future<EncryptResultDto> encryptEvent(
      {required List<int> groupId,
      required List<int> keyBundle,
      required EventDto event});

  /// Encrypt a `SyncApp` payload into the ring group, ready to be sent on the
  /// `/pair` WebSocket. Returns just the ciphertext bytes; the Dart caller
  /// never needs to construct an `EventDto` of an unsupported kind.
  Future<Uint8List> encryptSyncApp(
      {required List<int> ringGroupId,
      required List<int> keyBundle,
      required List<int> payload});

  /// Export the full session state as bytes for persistence.
  Future<Uint8List> exportState();

  /// Restore a session from previously exported state bytes.
  static Future<MoatSessionHandle> fromState({required List<int> state}) =>
      RustLib.instance.api
          .crateApiSimpleMoatSessionHandleFromState(state: state);

  /// Generate a new key package with DID and device name.
  /// Returns (key_package_bytes, key_bundle_bytes).
  Future<KeyPackageResult> generateKeyPackage(
      {required String did, required String deviceName});

  /// Get the DIDs of all members in a group (deduplicated).
  Future<List<String>> getGroupDids({required List<int> groupId});

  /// Get the current epoch of a group. Returns null if group doesn't exist.
  Future<BigInt?> getGroupEpoch({required List<int> groupId});

  /// Check if there are unsaved changes.
  bool hasPendingChanges();

  /// Check if a DID already has a device in the group.
  bool isDidInGroup({required List<int> groupId, required String did});

  /// Mark a tag as seen, advancing the seen counter for that sender.
  ///
  /// Call this after matching a tag from `populate_candidate_tags`.
  /// Returns true if the tag was found and the counter was updated.
  bool markTagSeen({required List<int> tag});

  /// Create a new session with empty state.
  static MoatSessionHandle newSession() =>
      RustLib.instance.api.crateApiSimpleMoatSessionHandleNewSession();

  /// Generate all candidate tags for every member in a group.
  ///
  /// Returns a flat list of candidate tags for recipient scanning.
  List<Uint8List> populateCandidateTags({required List<int> groupId});

  /// Process a welcome message to join a group. Returns the group ID.
  Future<Uint8List> processWelcome({required List<int> welcomeBytes});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RingDriverHandle>>
abstract class RingDriverHandle implements RustOpaqueInterface {
  /// Restore a ring driver from its persisted JSON state.
  static Future<RingDriverHandle> fromStateJson({required String json}) =>
      RustLib.instance.api
          .crateApiSimpleRingDriverHandleFromStateJson(json: json);

  /// Handle an incoming coord-group message (decrypted JSON payload).
  Future<List<RingCommandDto>> handleCoordMsg(
      {required MoatSessionHandle session,
      required String myDid,
      required List<int> groupId,
      required List<int> payload});

  /// Create a new ring driver with empty state.
  static RingDriverHandle newEmpty() =>
      RustLib.instance.api.crateApiSimpleRingDriverHandleNewEmpty();

  /// Cursor (rkey) for incremental own-PDS stealth scan.
  String? ownEventsCursor();

  /// Raw ring group ID, if a ring exists.
  Uint8List? ringGroupId();

  /// Drive one ring coordination tick. Returns commands for the host to interpret.
  Future<List<RingCommandDto>> tick(
      {required MoatSessionHandle session, required TickInputsDto inputs});

  /// Serialise the current ring driver state as JSON.
  Future<String> toStateJson();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncSessionHandle>>
abstract class SyncSessionHandle implements RustOpaqueInterface {
  /// Populate the plan for one conversation before calling `on_paired`.
  Future<void> addConvPlan(
      {required List<int> groupId,
      required String convId,
      required List<SyncMessageDto> ourMessages,
      required bool expectingBatch});

  /// `true` once the session has reached the `Done` phase.
  bool isDone();

  /// Create a new session in the `SendingHello` phase.
  static SyncSessionHandle newSession() =>
      RustLib.instance.api.crateApiSimpleSyncSessionHandleNewSession();

  /// Feed a received and decrypted `SyncMsg` (JSON bytes) into the state machine.
  Future<List<SyncOutputDto>> onMessage(
      {required List<int> msgBytes, required String ourDid});

  /// Called when the pair WS reaches the `paired` state.
  Future<List<SyncOutputDto>> onPaired(
      {required List<ConvStateDto> ourConvs, required BigInt ringEpoch});
}

class BlobEncryptResult {
  /// Encrypted bytes: nonce (24 bytes) || ciphertext.
  final Uint8List blob;

  /// 32-byte symmetric key.
  final Uint8List key;

  /// SHA-256 of blob (pre-decryption integrity check).
  final Uint8List ciphertextHash;

  /// SHA-256 of plaintext (post-decryption integrity check and cache key).
  final Uint8List contentHash;

  const BlobEncryptResult({
    required this.blob,
    required this.key,
    required this.ciphertextHash,
    required this.contentHash,
  });

  @override
  int get hashCode =>
      blob.hashCode ^
      key.hashCode ^
      ciphertextHash.hashCode ^
      contentHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlobEncryptResult &&
          runtimeType == other.runtimeType &&
          blob == other.blob &&
          key == other.key &&
          ciphertextHash == other.ciphertextHash &&
          contentHash == other.contentHash;
}

class ConvStateDto {
  final Uint8List groupId;
  final String? oldestRkey;
  final String? newestRkey;
  final Uint8List tipDigest;
  final List<SyncAnchorDto> anchors;

  const ConvStateDto({
    required this.groupId,
    this.oldestRkey,
    this.newestRkey,
    required this.tipDigest,
    required this.anchors,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      oldestRkey.hashCode ^
      newestRkey.hashCode ^
      tipDigest.hashCode ^
      anchors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvStateDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          oldestRkey == other.oldestRkey &&
          newestRkey == other.newestRkey &&
          tipDigest == other.tipDigest &&
          anchors == other.anchors;
}

class DecryptResultDto {
  final Uint8List newGroupState;
  final EventDto event;
  final SenderInfoDto? sender;

  /// Transcript integrity warnings (empty if none).
  final List<String> warnings;

  const DecryptResultDto({
    required this.newGroupState,
    required this.event,
    this.sender,
    required this.warnings,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      event.hashCode ^
      sender.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          event == other.event &&
          sender == other.sender &&
          warnings == other.warnings;
}

/// Result of decrypting a push notification payload.
class DecryptedPush {
  /// DID of the message sender, extracted from their MLS credential.
  final String? senderDid;

  /// Human-readable preview for the notification body (truncated to 200 chars).
  /// `None` for protocol messages (commit, welcome, checkpoint) that should not
  /// generate a visible notification.
  final String? plaintextPreview;

  /// The MLS group ID the message belongs to.
  final Uint8List groupId;

  /// 16-byte message ID for deduplication (present for Message and Reaction events).
  final Uint8List? messageId;

  const DecryptedPush({
    this.senderDid,
    this.plaintextPreview,
    required this.groupId,
    this.messageId,
  });

  @override
  int get hashCode =>
      senderDid.hashCode ^
      plaintextPreview.hashCode ^
      groupId.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedPush &&
          runtimeType == other.runtimeType &&
          senderDid == other.senderDid &&
          plaintextPreview == other.plaintextPreview &&
          groupId == other.groupId &&
          messageId == other.messageId;
}

/// Result of signing a Drawbridge challenge.
class DrawbridgeChallengeSignature {
  /// Ed25519 signature (64 bytes)
  final Uint8List signature;

  /// Ed25519 public key (32 bytes)
  final Uint8List publicKey;

  const DrawbridgeChallengeSignature({
    required this.signature,
    required this.publicKey,
  });

  @override
  int get hashCode => signature.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawbridgeChallengeSignature &&
          runtimeType == other.runtimeType &&
          signature == other.signature &&
          publicKey == other.publicKey;
}

class EncryptResultDto {
  final Uint8List newGroupState;
  final Uint8List tag;
  final Uint8List ciphertext;

  /// The message_id assigned to the event (16 bytes for Message/Reaction, None otherwise)
  final Uint8List? messageId;

  const EncryptResultDto({
    required this.newGroupState,
    required this.tag,
    required this.ciphertext,
    this.messageId,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      tag.hashCode ^
      ciphertext.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          tag == other.tag &&
          ciphertext == other.ciphertext &&
          messageId == other.messageId;
}

class EventDto {
  final EventKindDto kind;
  final Uint8List groupId;
  final BigInt epoch;
  final Uint8List payload;

  /// Unique message identifier (16 random bytes). Present for Message and Reaction events.
  final Uint8List? messageId;

  const EventDto({
    required this.kind,
    required this.groupId,
    required this.epoch,
    required this.payload,
    this.messageId,
  });

  /// Parse the payload as a reaction. Only valid when kind is Reaction.
  /// Returns None if this is not a Reaction event or if the payload is malformed.
  ReactionPayloadDto? reactionPayload() =>
      RustLib.instance.api.crateApiSimpleEventDtoReactionPayload(
        that: this,
      );

  @override
  int get hashCode =>
      kind.hashCode ^
      groupId.hashCode ^
      epoch.hashCode ^
      payload.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          groupId == other.groupId &&
          epoch == other.epoch &&
          payload == other.payload &&
          messageId == other.messageId;
}

enum EventKindDto {
  message,
  commit,
  welcome,
  checkpoint,
  reaction,
  unknown,
  ;
}

enum GroupKindDto {
  user,
  ring,
  deviceCoord,
  ;
}

class ImageProcessResult {
  /// Processed image bytes (JPEG or PNG, resized if >2048px).
  final Uint8List imageBytes;
  final int width;
  final int height;

  /// ThumbHash bytes for blurry placeholder preview.
  final Uint8List thumbhash;

  /// MIME type: "image/jpeg" or "image/png".
  final String mimeType;

  const ImageProcessResult({
    required this.imageBytes,
    required this.width,
    required this.height,
    required this.thumbhash,
    required this.mimeType,
  });

  @override
  int get hashCode =>
      imageBytes.hashCode ^
      width.hashCode ^
      height.hashCode ^
      thumbhash.hashCode ^
      mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageProcessResult &&
          runtimeType == other.runtimeType &&
          imageBytes == other.imageBytes &&
          width == other.width &&
          height == other.height &&
          thumbhash == other.thumbhash &&
          mimeType == other.mimeType;
}

class KeyPackageResult {
  final Uint8List keyPackage;
  final Uint8List keyBundle;

  const KeyPackageResult({
    required this.keyPackage,
    required this.keyBundle,
  });

  @override
  int get hashCode => keyPackage.hashCode ^ keyBundle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageResult &&
          runtimeType == other.runtimeType &&
          keyPackage == other.keyPackage &&
          keyBundle == other.keyBundle;
}

class OwnEventInputDto {
  final String rkey;
  final Uint8List ciphertext;

  const OwnEventInputDto({
    required this.rkey,
    required this.ciphertext,
  });

  @override
  int get hashCode => rkey.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OwnEventInputDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          ciphertext == other.ciphertext;
}

/// Reaction payload extracted from a Reaction event.
class ReactionPayloadDto {
  final String emoji;
  final Uint8List targetMessageId;

  const ReactionPayloadDto({
    required this.emoji,
    required this.targetMessageId,
  });

  @override
  int get hashCode => emoji.hashCode ^ targetMessageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReactionPayloadDto &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          targetMessageId == other.targetMessageId;
}

@freezed
sealed class RingCommandDto with _$RingCommandDto {
  const RingCommandDto._();

  const factory RingCommandDto.publishEvent({
    required Uint8List tag,
    required Uint8List ciphertext,
    required bool markOwn,
  }) = RingCommandDto_PublishEvent;
  const factory RingCommandDto.stealthPublishWelcome({
    required Uint8List tag,
    required Uint8List ciphertext,
  }) = RingCommandDto_StealthPublishWelcome;
  const factory RingCommandDto.replenishKeyPackage() =
      RingCommandDto_ReplenishKeyPackage;
  const factory RingCommandDto.registerGroup({
    required Uint8List groupId,
    required GroupKindDto kind,
  }) = RingCommandDto_RegisterGroup;
  const factory RingCommandDto.sendDrawbridgePairOffer({
    required Uint8List token,
  }) = RingCommandDto_SendDrawbridgePairOffer;
  const factory RingCommandDto.sendDrawbridgePairJoin({
    required Uint8List token,
  }) = RingCommandDto_SendDrawbridgePairJoin;
  const factory RingCommandDto.pollForNewDevices() =
      RingCommandDto_PollForNewDevices;
}

/// Information about the sender of a message, extracted from MLS credentials.
class SenderInfoDto {
  /// The sender's DID (e.g., "did:plc:abc123")
  final String did;

  /// The sender's device name (format: "did:plc:xxx/Device Name")
  final String deviceName;

  const SenderInfoDto({
    required this.did,
    required this.deviceName,
  });

  @override
  int get hashCode => did.hashCode ^ deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenderInfoDto &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          deviceName == other.deviceName;
}

class StealthKeypair {
  final Uint8List privateKey;
  final Uint8List publicKey;

  const StealthKeypair({
    required this.privateKey,
    required this.publicKey,
  });

  @override
  int get hashCode => privateKey.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StealthKeypair &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey &&
          publicKey == other.publicKey;
}

class SyncAnchorDto {
  final String rkey;
  final Uint8List digest;

  const SyncAnchorDto({
    required this.rkey,
    required this.digest,
  });

  @override
  int get hashCode => rkey.hashCode ^ digest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncAnchorDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          digest == other.digest;
}

class SyncMessageDto {
  final String rkey;
  final Uint8List? messageId;
  final String senderDid;
  final String senderDeviceName;
  final PlatformInt64 timestampMs;
  final String content;
  final bool isOwn;
  final String? blobUri;
  final Uint8List? blobKey;
  final Uint8List? blobCiphertextHash;
  final BigInt? blobCiphertextSize;
  final Uint8List? blobContentHash;
  final String? blobMime;
  final int? blobWidth;
  final int? blobHeight;

  const SyncMessageDto({
    required this.rkey,
    this.messageId,
    required this.senderDid,
    required this.senderDeviceName,
    required this.timestampMs,
    required this.content,
    required this.isOwn,
    this.blobUri,
    this.blobKey,
    this.blobCiphertextHash,
    this.blobCiphertextSize,
    this.blobContentHash,
    this.blobMime,
    this.blobWidth,
    this.blobHeight,
  });

  @override
  int get hashCode =>
      rkey.hashCode ^
      messageId.hashCode ^
      senderDid.hashCode ^
      senderDeviceName.hashCode ^
      timestampMs.hashCode ^
      content.hashCode ^
      isOwn.hashCode ^
      blobUri.hashCode ^
      blobKey.hashCode ^
      blobCiphertextHash.hashCode ^
      blobCiphertextSize.hashCode ^
      blobContentHash.hashCode ^
      blobMime.hashCode ^
      blobWidth.hashCode ^
      blobHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncMessageDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          messageId == other.messageId &&
          senderDid == other.senderDid &&
          senderDeviceName == other.senderDeviceName &&
          timestampMs == other.timestampMs &&
          content == other.content &&
          isOwn == other.isOwn &&
          blobUri == other.blobUri &&
          blobKey == other.blobKey &&
          blobCiphertextHash == other.blobCiphertextHash &&
          blobCiphertextSize == other.blobCiphertextSize &&
          blobContentHash == other.blobContentHash &&
          blobMime == other.blobMime &&
          blobWidth == other.blobWidth &&
          blobHeight == other.blobHeight;
}

@freezed
sealed class SyncOutputDto with _$SyncOutputDto {
  const SyncOutputDto._();

  /// JSON-encoded `SyncMsg` ready to be encrypted via ring MLS and sent on the pair WS.
  const factory SyncOutputDto.send({
    required Uint8List bytes,
  }) = SyncOutputDto_Send;

  /// Persist these messages for the conversation `conv_id` (hex group ID).
  const factory SyncOutputDto.store({
    required String convId,
    required List<SyncMessageDto> messages,
  }) = SyncOutputDto_Store;

  /// Sync is complete; close the pair WS and tear down.
  const factory SyncOutputDto.complete() = SyncOutputDto_Complete;
}

class ThumbHashResult {
  /// Raw RGBA pixel data (width * height * 4 bytes).
  final Uint8List rgba;
  final int width;
  final int height;

  const ThumbHashResult({
    required this.rgba,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => rgba.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbHashResult &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba &&
          width == other.width &&
          height == other.height;
}

class TickInputsDto {
  /// Sibling key packages fetched from our own PDS (driver filters out our own).
  final List<Uint8List> keyPackages;

  /// Stealth scan-pubkeys (32 bytes each) for all of our devices.
  final List<Uint8List> stealthPubkeys;

  /// Own-PDS events since `own_events_cursor`.
  final List<OwnEventInputDto> ownEvents;

  /// Our stealth scan private key (32 bytes).
  final Uint8List stealthPrivkey;

  /// Our DID.
  final String did;

  /// Our device name.
  final String deviceName;

  /// Identity key bundle.
  final Uint8List keyBundle;

  /// Wall-clock time (ms since epoch); used as `ring_created_at` for new rings.
  final PlatformInt64 nowMs;

  /// Whether the host's main Drawbridge WS is connected.
  final bool drawbridgeHasOwnConnection;

  /// Whether a sync session is already running.
  final bool syncSessionActive;

  const TickInputsDto({
    required this.keyPackages,
    required this.stealthPubkeys,
    required this.ownEvents,
    required this.stealthPrivkey,
    required this.did,
    required this.deviceName,
    required this.keyBundle,
    required this.nowMs,
    required this.drawbridgeHasOwnConnection,
    required this.syncSessionActive,
  });

  @override
  int get hashCode =>
      keyPackages.hashCode ^
      stealthPubkeys.hashCode ^
      ownEvents.hashCode ^
      stealthPrivkey.hashCode ^
      did.hashCode ^
      deviceName.hashCode ^
      keyBundle.hashCode ^
      nowMs.hashCode ^
      drawbridgeHasOwnConnection.hashCode ^
      syncSessionActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TickInputsDto &&
          runtimeType == other.runtimeType &&
          keyPackages == other.keyPackages &&
          stealthPubkeys == other.stealthPubkeys &&
          ownEvents == other.ownEvents &&
          stealthPrivkey == other.stealthPrivkey &&
          did == other.did &&
          deviceName == other.deviceName &&
          keyBundle == other.keyBundle &&
          nowMs == other.nowMs &&
          drawbridgeHasOwnConnection == other.drawbridgeHasOwnConnection &&
          syncSessionActive == other.syncSessionActive;
}

class WelcomeResultDto {
  final Uint8List newGroupState;
  final Uint8List welcome;
  final Uint8List commit;
  final Uint8List groupId;

  const WelcomeResultDto({
    required this.newGroupState,
    required this.welcome,
    required this.commit,
    required this.groupId,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      welcome.hashCode ^
      commit.hashCode ^
      groupId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WelcomeResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          welcome == other.welcome &&
          commit == other.commit &&
          groupId == other.groupId;
}
