// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `credential_from_dto`, `from_core`, `into_core`, `payload_from_core`, `payload_to_core`, `push_media_label`, `push_plaintext_preview`, `sibling_info_to_core`, `to_core_sibling_stealth`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MoatError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Generate a stealth keypair. Returns (private_key, public_key) each 32 bytes.
StealthKeypair generateStealthKeypair() =>
    RustLib.instance.api.crateApiSimpleGenerateStealthKeypair();

/// Encrypt a Welcome for one or more recipients' stealth addresses (multi-device support).
/// Each recipient pubkey must be 32 bytes.
Future<Uint8List> encryptForStealth(
        {required List<Uint8List> recipientScanPubkeys,
        required List<int> welcomeBytes}) =>
    RustLib.instance.api.crateApiSimpleEncryptForStealth(
        recipientScanPubkeys: recipientScanPubkeys, welcomeBytes: welcomeBytes);

/// Try to decrypt a stealth-encrypted payload. Returns None if not for us.
Uint8List? tryDecryptStealth(
        {required List<int> scanPrivkey, required List<int> payload}) =>
    RustLib.instance.api.crateApiSimpleTryDecryptStealth(
        scanPrivkey: scanPrivkey, payload: payload);

/// Generate candidate tags for recipient scanning.
///
/// Returns a list of (tag, counter) pairs for the given sender in the group.
List<Uint8List> generateCandidateTags(
        {required MoatSessionHandle handle,
        required List<int> groupId,
        required String senderDid,
        required List<int> senderDeviceId,
        required BigInt fromCounter,
        required BigInt count}) =>
    RustLib.instance.api.crateApiSimpleGenerateCandidateTags(
        handle: handle,
        groupId: groupId,
        senderDid: senderDid,
        senderDeviceId: senderDeviceId,
        fromCounter: fromCounter,
        count: count);

/// Derive the next unique tag for publishing an event (increments counter).
Uint8List deriveNextTag(
        {required MoatSessionHandle handle,
        required List<int> groupId,
        required List<int> keyBundle}) =>
    RustLib.instance.api.crateApiSimpleDeriveNextTag(
        handle: handle, groupId: groupId, keyBundle: keyBundle);

/// Sign a Drawbridge challenge with the Ed25519 identity key from a key bundle.
///
/// Returns (signature_bytes, public_key_bytes) as raw bytes (64 and 32 bytes).
/// The caller is responsible for base64-encoding for JSON transport.
///
/// `message` is typically `"{nonce}\n{relay_url}\n{timestamp}\n"`.
Future<DrawbridgeChallengeSignature> signDrawbridgeChallenge(
        {required List<int> keyBundle, required List<int> message}) =>
    RustLib.instance.api.crateApiSimpleSignDrawbridgeChallenge(
        keyBundle: keyBundle, message: message);

/// Pad plaintext to bucket size (512, 1024, or 4096 bytes).
///
/// Fails above the largest bucket: there is nothing to round up to, and
/// oversized content belongs in an external blob with only the reference
/// in the event.
Uint8List padToBucket({required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimplePadToBucket(plaintext: plaintext);

/// Frame plaintext with a length prefix but no bucket padding, for frames
/// that never become PDS records. See `moat_core::frame_unpadded`.
Uint8List frameUnpadded({required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimpleFrameUnpadded(plaintext: plaintext);

/// Remove padding and extract original plaintext.
Uint8List unpad({required List<int> padded}) =>
    RustLib.instance.api.crateApiSimpleUnpad(padded: padded);

/// Encrypt a blob. Returns encrypted bytes and metadata for ExternalBlob.
Future<BlobEncryptResult> blobEncrypt({required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimpleBlobEncrypt(plaintext: plaintext);

/// Decrypt and verify a blob.
Future<Uint8List> blobDecrypt(
        {required List<int> blob,
        required List<int> key,
        required List<int> ciphertextHash,
        required List<int> contentHash}) =>
    RustLib.instance.api.crateApiSimpleBlobDecrypt(
        blob: blob,
        key: key,
        ciphertextHash: ciphertextHash,
        contentHash: contentHash);

/// Process an image for sending: validate format, resize if >2048px, generate thumbhash.
/// Returns processed bytes, dimensions, thumbhash, and MIME type.
Future<ImageProcessResult> processImageForSend(
        {required List<int> imageBytes}) =>
    RustLib.instance.api
        .crateApiSimpleProcessImageForSend(imageBytes: imageBytes);

/// Decode a thumbhash to RGBA pixels for placeholder rendering.
Future<ThumbHashResult> decodeThumbhash({required List<int> hash}) =>
    RustLib.instance.api.crateApiSimpleDecodeThumbhash(hash: hash);

/// Decrypt a push notification payload for use in a background message handler
/// or iOS Notification Service Extension.
///
/// Reads the MLS session state from `state_path`, scans `group_ids` to find
/// which group the `tag` belongs to, decrypts `ciphertext`, advances the seen
/// counter, and writes the updated state back to `state_path` atomically
/// (write to `<state_path>.push_tmp`, then rename).
///
/// Returns `Err` if the tag is not matched in any group or if decrypt fails.
///
/// # Concurrency
/// The rename is atomic on POSIX. If the foreground app races to write state
/// simultaneously one update will win; the dedup map in moat-core makes
/// double-processing safe.
Future<DecryptedPush> decryptPushPayload(
        {required String statePath,
        required List<Uint8List> groupIds,
        required List<int> tag,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiSimpleDecryptPushPayload(
        statePath: statePath,
        groupIds: groupIds,
        tag: tag,
        ciphertext: ciphertext);

/// Encode `token`+`secret` to the hyphen-grouped Crockford base32 text form
/// (`MZXW6-YTBOI-…`), for manual entry / display beneath a QR code.
Future<String> pairingPayloadToText(
        {required List<int> token, required List<int> secret}) =>
    RustLib.instance.api
        .crateApiSimplePairingPayloadToText(token: token, secret: secret);

/// Decode a pairing code's text form back into token+secret.
Future<PairingPayloadDto> pairingPayloadFromText({required String text}) =>
    RustLib.instance.api.crateApiSimplePairingPayloadFromText(text: text);

/// Encode `token`+`secret` to the `moat-pair:` URI form used for the QR payload.
Future<String> pairingPayloadToUri(
        {required List<int> token, required List<int> secret}) =>
    RustLib.instance.api
        .crateApiSimplePairingPayloadToUri(token: token, secret: secret);

/// Decode a `moat-pair:` URI back into token+secret.
Future<PairingPayloadDto> pairingPayloadFromUri({required String uri}) =>
    RustLib.instance.api.crateApiSimplePairingPayloadFromUri(uri: uri);

/// Encode a `RingMsg::SyncRequest` for publication on the device ring as
/// an `EventKindDto::RingMsg` event payload.
Future<Uint8List> ringMsgEncodeSyncRequest(
        {required List<int> token, Uint8List? targetDeviceId}) =>
    RustLib.instance.api.crateApiSimpleRingMsgEncodeSyncRequest(
        token: token, targetDeviceId: targetDeviceId);

/// Build a `ring.msg` payload offering history to one sibling. Always
/// targeted — the relay admits two attaches, so an untargeted offer would
/// pick its recipient arbitrarily.
Future<Uint8List> ringMsgEncodeSyncOffer(
        {required List<int> token, required List<int> targetDeviceId}) =>
    RustLib.instance.api.crateApiSimpleRingMsgEncodeSyncOffer(
        token: token, targetDeviceId: targetDeviceId);

/// Decode a `ring.msg` payload and return the sync request's rendezvous
/// token. Errors on anything that is not a well-formed `RingMsg`.
Future<Uint8List> ringMsgDecodeSyncRequest({required List<int> payload}) =>
    RustLib.instance.api
        .crateApiSimpleRingMsgDecodeSyncRequest(payload: payload);

/// Decode any `ring.msg` payload.
Future<RingMsgDto> ringMsgDecode({required List<int> payload}) =>
    RustLib.instance.api.crateApiSimpleRingMsgDecode(payload: payload);

/// Build a `ring.msg` payload advertising what this device holds. The
/// conversation list itself lives in the blob the reference points at.
Future<Uint8List> ringMsgEncodeHistorySummary(
        {required String uri,
        required List<int> key,
        required List<int> ciphertextHash,
        required BigInt ciphertextSize,
        required List<int> contentHash}) =>
    RustLib.instance.api.crateApiSimpleRingMsgEncodeHistorySummary(
        uri: uri,
        key: key,
        ciphertextHash: ciphertextHash,
        ciphertextSize: ciphertextSize,
        contentHash: contentHash);

/// Encode the summary blob's plaintext.
Future<Uint8List> historySummaryEncode({required List<ConvSummaryDto> convs}) =>
    RustLib.instance.api.crateApiSimpleHistorySummaryEncode(convs: convs);

/// Decode the summary blob's plaintext.
Future<List<ConvSummaryDto>> historySummaryDecode({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSimpleHistorySummaryDecode(bytes: bytes);

/// How long a published sync request stays valid, matching the relay's
/// token TTL.
PlatformInt64 syncRequestTtlMs() =>
    RustLib.instance.api.crateApiSimpleSyncRequestTtlMs();

/// Byte budget for all inventories in one `Hello` — see
/// `fit_hello_inventories`.
int helloInventoryBudgetBytes() =>
    RustLib.instance.api.crateApiSimpleHelloInventoryBudgetBytes();

/// Fit a Hello's inventories inside that budget by downgrading the largest
/// enumerations to spans, so the frame stays under the relay's hard limit.
Future<List<ConvStateDto>> fitHelloInventories(
        {required List<ConvStateDto> convs}) =>
    RustLib.instance.api.crateApiSimpleFitHelloInventories(convs: convs);

/// Seal a frame with AES-128-GCM under the pairing channel's directional
/// key (`key` must be 16 bytes — one of `channel_key_new_to_old`/
/// `channel_key_old_to_new`). Used to run the pairing-AEAD history-sync
/// phase after `is_done()`, continuing the counter sequence — never reuse
/// a counter value under the same key.
Future<Uint8List> pairingSealFrame(
        {required List<int> key,
        required BigInt counter,
        required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimplePairingSealFrame(
        key: key, counter: counter, plaintext: plaintext);

/// Open a frame sealed by [`pairing_seal_frame`].
Future<Uint8List> pairingOpenFrame(
        {required List<int> key,
        required BigInt counter,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiSimplePairingOpenFrame(
        key: key, counter: counter, ciphertext: ciphertext);

/// `true` if `plaintext` (already opened under the pairing AEAD) decodes
/// as the pairing session's advisory `Done` courtesy rather than a
/// `SyncMsg`. Used by the post-Done pairing-sync phase to recognize and
/// ignore a `Done` that arrives after the local side has already
/// transitioned to sync-frame dispatch — see the note on
/// `PairingCommandDto.startSync` for why this can happen even in a
/// well-behaved exchange.
bool pairingFrameIsDone({required List<int> plaintext}) =>
    RustLib.instance.api.crateApiSimplePairingFrameIsDone(plaintext: plaintext);

/// How many fresh KeyPackages a new device should seed the approver's pool
/// with via `Enroll.conv_kps` — `moat_core::device_ring::KP_POOL_TARGET`,
/// exposed so hosts building that batch (e.g. `PairingService.dart`) don't
/// hand-duplicate the literal.
BigInt kpPoolTarget() => RustLib.instance.api.crateApiSimpleKpPoolTarget();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MoatSessionHandle>>
abstract class MoatSessionHandle implements RustOpaqueInterface {
  /// Add a member to a group. Returns welcome result.
  Future<WelcomeResultDto> addMember(
      {required List<int> groupId,
      required List<int> keyBundle,
      required List<int> newMemberKeyPackage});

  /// Create a new MLS group with DID and device name. Returns the group ID.
  Future<Uint8List> createGroup(
      {required String did,
      required String deviceName,
      required List<int> keyBundle});

  /// Decrypt a ciphertext for a group. Returns decrypt result with any warnings.
  Future<DecryptResultDto> decryptEvent(
      {required List<int> groupId, required List<int> ciphertext});

  /// Decrypt an incoming `/pair` WS binary frame as a `SyncApp` event in the
  /// ring group. Returns the inner payload bytes (`SyncMsg` JSON) alongside
  /// the sending device as MLS named it, or an error if decrypt failed or
  /// the event was not a `SyncApp`.
  Future<SyncFrameDto> decryptSyncFrame(
      {required List<int> ringGroupId, required List<int> ciphertext});

  /// Get the 16-byte device ID.
  Uint8List deviceId();

  /// Encrypt an event for a group. Returns encrypt result.
  Future<EncryptResultDto> encryptEvent(
      {required List<int> groupId,
      required List<int> keyBundle,
      required EventDto event});

  /// Encrypt a `SyncApp` payload into the ring group, ready to be sent on the
  /// `/pair` WebSocket. Returns just the ciphertext bytes; the Dart caller
  /// never needs to construct an `EventDto` of an unsupported kind.
  Future<Uint8List> encryptSyncApp(
      {required List<int> ringGroupId,
      required List<int> keyBundle,
      required List<int> payload});

  /// Export the full session state as bytes for persistence.
  Future<Uint8List> exportState();

  /// Extract the credential (DID, device_id, device_name) from a raw key package bytes.
  /// Returns None if the key package has no credential embedded.
  Future<CredentialDto?> extractCredentialFromKeyPackage(
      {required List<int> keyPackage});

  /// Restore a session from previously exported state bytes.
  static Future<MoatSessionHandle> fromState({required List<int> state}) =>
      RustLib.instance.api
          .crateApiSimpleMoatSessionHandleFromState(state: state);

  /// Generate a new key package with DID and device name.
  /// Returns (key_package_bytes, key_bundle_bytes).
  Future<KeyPackageResult> generateKeyPackage(
      {required String did, required String deviceName});

  /// Get the DIDs of all members in a group (deduplicated).
  Future<List<String>> getGroupDids({required List<int> groupId});

  /// Get the current epoch of a group. Returns null if group doesn't exist.
  Future<BigInt?> getGroupEpoch({required List<int> groupId});

  /// Return the (DID, device_id, device_name) credential for every member of a group.
  Future<List<CredentialDto>> getGroupMemberCredentials(
      {required List<int> groupId});

  /// Check if there are unsaved changes.
  bool hasPendingChanges();

  /// Check if a DID already has a device in the group.
  bool isDidInGroup({required List<int> groupId, required String did});

  /// Mark a tag as seen, advancing the seen counter for that sender.
  ///
  /// Call this after matching a tag from `populate_candidate_tags`.
  /// Returns true if the tag was found and the counter was updated.
  bool markTagSeen({required List<int> tag});

  /// Create a new session with empty state.
  static MoatSessionHandle newSession() =>
      RustLib.instance.api.crateApiSimpleMoatSessionHandleNewSession();

  /// Generate all candidate tags for every member in a group.
  ///
  /// Returns a flat list of candidate tags for recipient scanning.
  List<Uint8List> populateCandidateTags({required List<int> groupId});

  /// Process a welcome message to join a group. Returns the group ID.
  Future<Uint8List> processWelcome({required List<int> welcomeBytes});

  /// Generate a fresh key package reusing the **existing** signing key from `key_bundle`.
  ///
  /// Unlike `generate_key_package`, this preserves the leaf-node public key so that
  /// all MLS groups the caller already belongs to remain usable after the call.
  /// Use this to replenish the PDS key package after a Welcome has consumed the
  /// previous one (e.g. after joining a coord group).
  ///
  /// Returns only the new key package bytes; the key bundle is unchanged.
  Future<Uint8List> replenishKeyPackage(
      {required String did,
      required String deviceName,
      required List<int> keyBundle});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PairingSessionHandle>>
abstract class PairingSessionHandle implements RustOpaqueInterface {
  /// Existing device only: called once the user taps Approve. Creates
  /// the ring (first pairing) or adds the joiner (subsequent pairings),
  /// seeds the newcomer's KP pool, and emits the sealed `Admit` frame.
  Future<List<PairingCommandDto>> approve(
      {required MoatSessionHandle session,
      required CredentialDto credential,
      required List<int> keyBundle,
      required List<int> ownStealthPubkey,
      required List<SiblingInfoDto> knownSiblings,
      Uint8List? existingRingId});

  /// Either role: abort an in-flight pairing before it reaches a terminal
  /// state, moving the session to `Failed`. Errors, without changing the
  /// session's state, if it has already reached a terminal state.
  void cancel();

  /// The new-device→existing-device directional AEAD key, for
  /// continuing the pairing-AEAD stream past `is_done()` (the history
  /// sync handoff) — see `next_send_counter`/`next_recv_counter`.
  Uint8List channelKeyNewToOld();

  /// The existing-device→new-device directional AEAD key.
  Uint8List channelKeyOldToNew();

  /// Construct a session for the existing (approving) device.
  static PairingSessionHandle existingDevice(
          {required List<int> secret, required List<int> token}) =>
      RustLib.instance.api.crateApiSimplePairingSessionHandleExistingDevice(
          secret: secret, token: token);

  /// `true` once this session has reached its terminal `Done` phase.
  bool isDone();

  /// Construct a session for the new (joining) device.
  static PairingSessionHandle newDevice(
          {required List<int> secret, required List<int> token}) =>
      RustLib.instance.api.crateApiSimplePairingSessionHandleNewDevice(
          secret: secret, token: token);

  /// Next unused counter for frames *we* expect to receive.
  BigInt nextRecvCounter();

  /// Next unused counter for frames *we* send, continuing this session's
  /// own sequence — never reuse a value already used during Enroll/Admit/Done.
  BigInt nextSendCounter();

  /// Feed a sealed frame received over the pair channel. Dispatches on
  /// role + phase; a decryption or ordering-violation error aborts the
  /// session (returned as `Err`).
  Future<List<PairingCommandDto>> onFrameReceived(
      {required MoatSessionHandle session,
      required CredentialDto ownCredential,
      required List<int> ciphertext});

  /// Existing device only: the peer's `Enroll`, once received, pending
  /// the user's approval decision.
  EnrollDto? pendingEnroll();

  /// Existing device only: decline a pending `Enroll`, moving the session
  /// to `Failed`. Errors, without changing the session's state, if there
  /// is no pending `Enroll` to reject (including an already-terminal
  /// session).
  void reject();

  /// The ring this session ended up in, once known.
  Uint8List? ringId();

  /// New device: build and seal the `Enroll` frame once the pair channel
  /// reaches `paired`.
  Future<List<PairingCommandDto>> startEnroll(
      {required MoatSessionHandle session,
      required CredentialDto credential,
      required List<int> keyBundle,
      required List<int> stealthScanPubkey,
      required List<OfferedKpDto> convKps});

  /// Render this session's current state for UI presentation — mirrors
  /// `moat_core::PairingSession::ui_state`. The single source of truth
  /// every render/dispatch site (`PairingService.state`, `/pair/status`)
  /// reads instead of deriving its own.
  PairingUiStateDto uiState();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RingDriverHandle>>
abstract class RingDriverHandle implements RustOpaqueInterface {
  /// Allocate `count` fresh, monotonic KP sequence numbers from this
  /// device's own owner-global counter — must go through here (not a
  /// host-local counter) so seqs never collide with ones allocated
  /// elsewhere for a different purpose (e.g. steady-state KP-lane
  /// batches). Used by `PairingService.startEnroll` to build
  /// `Enroll.conv_kps` without a separate FFI surface per caller.
  Uint64List allocateKpSeqs({required BigInt count});

  /// Claim one unused key package from the local pool for `owner`, marking
  /// its seq consumed.  `None` means the pool is drained — the host should
  /// emit a `KpRequest` via [`Self::emit_kp_request_for`] and defer the add
  /// until a `KpBatch` arrives.  Single-use enforcement lives here, not in
  /// the host: a seq is never returned twice, even if replayed into the
  /// pool.
  OfferedKpDto? claimKp({required List<int> ownerDeviceId});

  /// One-line snapshot of ring membership and peer states, for the Dart
  /// host's debug log. Same renderer as `moat-cli` uses, so a mixed-runtime
  /// beacon failure produces comparable lines from both sides.
  String debugSummary();

  /// Mark a sibling's current advertisement as already asked about, so
  /// it stops prompting until that sibling says something new.
  void dismissSiblingSummary({required List<int> deviceId});

  /// Emit a `KpRequest` to `owner` asking it to top up our pool.  The host
  /// publishes the returned commands.  Empty if not in a ring or if the
  /// sibling's stealth record is not yet known (self-healing: the next poll
  /// retries).
  Future<List<RingCommandDto>> emitKpRequestFor(
      {required MoatSessionHandle session,
      required String myDid,
      required List<int> keyBundle,
      required List<SiblingStealthDto> siblingStealth,
      required List<int> ownerDeviceId});

  /// Build the stealth-publish command carrying a `CoordMsg::UserConvWelcome`
  /// for `owner`.  The CoordMsg framing stays in Rust so the wire format has
  /// a single owner.  `None` if not in a ring or the sibling's stealth
  /// record is unknown.
  ///
  /// Flat parameter list rather than a bundled struct: each `#[frb]`
  /// parameter becomes a named argument in the generated Dart binding, so
  /// callers get the same readability a struct would give without an
  /// extra DTO to keep in sync.
  Future<RingCommandDto?> encryptUserConvWelcome(
      {required MoatSessionHandle session,
      required String myDid,
      required List<int> keyBundle,
      required List<SiblingStealthDto> siblingStealth,
      required List<int> ownerDeviceId,
      required List<int> groupId,
      required List<int> welcome});

  /// Restore a ring state from its persisted JSON.
  static Future<RingDriverHandle> fromStateJson({required String json}) =>
      RustLib.instance.api
          .crateApiSimpleRingDriverHandleFromStateJson(json: json);

  /// Seed `owner`'s consumer-side pool with a freshly-received batch.
  /// Mirrors `moat-cli`'s `PairingCommandDto.seedKpPool` handling — the
  /// existing device calls this with the newcomer's `Enroll.conv_kps` on
  /// Approve, seeding the newcomer's pool directly instead of a
  /// KpRequest/KpBatch round trip over the stealth lane.
  void ingestKpBatch(
      {required List<int> ownerDeviceId, required List<OfferedKpDto> kps});

  /// Create a new ring state with empty state.
  static RingDriverHandle newEmpty() =>
      RustLib.instance.api.crateApiSimpleRingDriverHandleNewEmpty();

  /// Siblings worth prompting the user to send history to: ones that
  /// have advertised holding less than `our_messages`, and that the
  /// user has not already answered. Returns hex device ids.
  ///
  /// The rule itself lives in moat-core so both runtimes decide
  /// identically — see `DeviceRingState::offerable_siblings`.
  List<String> offerableSiblings({required BigInt ourMessages});

  /// Cursor (rkey) for incremental own-PDS stealth scan.
  String? ownEventsCursor();

  /// The record URI of our last published summary, which the next
  /// publish supersedes and should delete.
  String? publishedSummaryRecord();

  /// Record that we are now an MLS member of `ring_id`, looking up our
  /// own leaf index from the group's member list. Called once, host-side,
  /// when a pairing exchange completes — the new device from
  /// `PairingCommandDto.persistRing`, the existing device right after a
  /// successful `PairingSessionHandle.approve` (which has no command of
  /// its own for this, since it already knows it just created/joined
  /// `ring_id`). Mirrors `moat-cli`'s `App`-level interpreter.
  Future<void> recordRingMembership(
      {required MoatSessionHandle session,
      required List<int> ringId,
      required PlatformInt64 nowMs});

  /// Record a sibling's advertisement, replacing whatever it said
  /// before. A dismissal is carried over only when the contents are
  /// unchanged — a sibling that now holds something different is
  /// asking a different question.
  void recordSiblingSummary(
      {required List<int> deviceId,
      required List<ConvSummaryDto> convs,
      required PlatformInt64 receivedAtMs});

  /// Raw ring group ID, if a ring exists.
  Uint8List? ringGroupId();

  /// Device ids of siblings confirmed to be in the ring.  Drives the
  /// same-user fan-out loop in the host.
  List<Uint8List> ringJoinedSiblings({required MoatSessionHandle session});

  /// Record the URI of the summary we just published.
  void setPublishedSummaryRecord({String? uri});

  /// Every advertisement this device holds.
  List<SiblingSummaryDto> siblingSummaries();

  /// Drive one ring coordination tick. Returns commands for the host to interpret.
  Future<List<RingCommandDto>> tick(
      {required MoatSessionHandle session, required TickInputsDto inputs});

  /// Serialise the current ring state as JSON.
  Future<String> toStateJson();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncRequestSessionHandle>>
abstract class SyncRequestSessionHandle implements RustOpaqueInterface {
  /// The user approved a sibling's request. Returns the token to
  /// `pair_join` with; errors if no decision is outstanding.
  Uint8List accept();

  /// A sibling offered us history and we are joining its rendezvous.
  /// No prompt: the offer already carries the one human decision, made
  /// on the side that could judge.
  static SyncRequestSessionHandle acceptOffer(
          {required List<int> token, required PlatformInt64 nowMs}) =>
      RustLib.instance.api.crateApiSimpleSyncRequestSessionHandleAcceptOffer(
          token: token, nowMs: nowMs);

  /// The user declined. Local only — nothing goes on the wire, so one
  /// refusal among several prompted siblings doesn't cancel the request.
  void decline();

  /// Move an unanswered session to `Failed` once its rendezvous has
  /// outlived the relay's token TTL. Returns `true` only on the call
  /// that changed the state, so a host driving this from a periodic
  /// tick has exactly one edge to react to.
  bool expireIfDue({required PlatformInt64 nowMs});

  /// Terminal failure. The first reason wins — a late teardown notice
  /// never overwrites the failure that explains the outcome, nor a
  /// completed transfer.
  void fail({required SyncFailureDto reason});

  /// `true` once the rendezvous token has outlived the relay's TTL. Only
  /// the rendezvous is bounded; a session that reached the channel runs
  /// to completion however long the transfer takes.
  bool isExpired({required PlatformInt64 nowMs});

  /// `true` once the session can no longer change state.
  bool isTerminal();

  /// Offer history to a sibling that does not have it. The offerer's
  /// user has already approved — that is what produced this call — so
  /// neither side prompts again.
  static SyncRequestSessionHandle offer(
          {required List<int> token, required PlatformInt64 nowMs}) =>
      RustLib.instance.api.crateApiSimpleSyncRequestSessionHandleOffer(
          token: token, nowMs: nowMs);

  /// The pair channel reached `paired`.
  void onChannelUp();

  /// The sync session running on this channel finished. `tally` comes
  /// from that session; `device_name` is the peer as MLS named it on the
  /// frames it sent.
  void onComplete({required SyncTallyDto tally, String? deviceName});

  /// A sibling's request arrived on the ring. `device_name` must come
  /// from the sender's MLS leaf credential, not from the payload.
  static SyncRequestSessionHandle received(
          {required List<int> token,
          required String deviceName,
          required PlatformInt64 nowMs}) =>
      RustLib.instance.api.crateApiSimpleSyncRequestSessionHandleReceived(
          token: token, deviceName: deviceName, nowMs: nowMs);

  /// Start a request of our own. The caller publishes
  /// `ring_msg_encode_sync_request(token)` on the ring and registers the
  /// same token with the relay via `pair_offer`.
  static SyncRequestSessionHandle request(
          {required List<int> token, required PlatformInt64 nowMs}) =>
      RustLib.instance.api.crateApiSimpleSyncRequestSessionHandleRequest(
          token: token, nowMs: nowMs);

  /// The rendezvous token this session is bound to.
  Uint8List token();

  /// Current projection. Computed fresh, never cached.
  SyncRequestUiStateDto uiState();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncSessionHandle>>
abstract class SyncSessionHandle implements RustOpaqueInterface {
  /// Populate the plan for one conversation before calling `on_paired`.
  Future<void> addConvPlan(
      {required List<int> groupId,
      required String convId,
      required List<SyncMessageDto> ourMessages,
      required bool expectingBatch});

  /// `true` once the session has reached the `Done` phase.
  bool isDone();

  /// Create a new session in the `SendingHello` phase.
  static SyncSessionHandle newSession() =>
      RustLib.instance.api.crateApiSimpleSyncSessionHandleNewSession();

  /// Feed a received and decrypted `SyncMsg` (JSON bytes) into the state machine.
  Future<List<SyncOutputDto>> onMessage({required List<int> msgBytes});

  /// Called when the pair WS reaches the `paired` state.
  Future<List<SyncOutputDto>> onPaired(
      {required List<ConvStateDto> ourConvs, required BigInt ringEpoch});

  /// What this side has received. Read at completion, where it becomes
  /// the report the user sees.
  SyncTallyDto tally();
}

class BlobEncryptResult {
  /// Encrypted bytes: nonce (24 bytes) || ciphertext.
  final Uint8List blob;

  /// 32-byte symmetric key.
  final Uint8List key;

  /// SHA-256 of blob (pre-decryption integrity check).
  final Uint8List ciphertextHash;

  /// SHA-256 of plaintext (post-decryption integrity check and cache key).
  final Uint8List contentHash;

  const BlobEncryptResult({
    required this.blob,
    required this.key,
    required this.ciphertextHash,
    required this.contentHash,
  });

  @override
  int get hashCode =>
      blob.hashCode ^
      key.hashCode ^
      ciphertextHash.hashCode ^
      contentHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlobEncryptResult &&
          runtimeType == other.runtimeType &&
          blob == other.blob &&
          key == other.key &&
          ciphertextHash == other.ciphertextHash &&
          contentHash == other.contentHash;
}

@freezed
sealed class ConvInventoryDto with _$ConvInventoryDto {
  const ConvInventoryDto._();

  /// Every rkey held, enumerated. The peer sends exactly the complement.
  const factory ConvInventoryDto.complete({
    required List<String> rkeys,
  }) = ConvInventoryDto_Complete;

  /// Too large for the Hello's byte budget, so only the span is given.
  const factory ConvInventoryDto.range({
    required String oldest,
    required String newest,
    required BigInt count,
  }) = ConvInventoryDto_Range;

  /// Nothing held at all.
  const factory ConvInventoryDto.empty() = ConvInventoryDto_Empty;
}

class ConvStateDto {
  final Uint8List groupId;
  final ConvInventoryDto inventory;

  const ConvStateDto({
    required this.groupId,
    required this.inventory,
  });

  @override
  int get hashCode => groupId.hashCode ^ inventory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvStateDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          inventory == other.inventory;
}

/// What one device holds for one conversation, as advertised.
class ConvSummaryDto {
  final Uint8List groupId;
  final ConvInventoryDto inventory;

  const ConvSummaryDto({
    required this.groupId,
    required this.inventory,
  });

  @override
  int get hashCode => groupId.hashCode ^ inventory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvSummaryDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          inventory == other.inventory;
}

/// Credential fields for a group member or key package.
class CredentialDto {
  final String did;
  final Uint8List deviceId;
  final String deviceName;

  const CredentialDto({
    required this.did,
    required this.deviceId,
    required this.deviceName,
  });

  @override
  int get hashCode => did.hashCode ^ deviceId.hashCode ^ deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CredentialDto &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName;
}

class DecryptResultDto {
  final Uint8List newGroupState;
  final EventDto event;
  final SenderInfoDto? sender;

  /// Transcript integrity warnings (empty if none).
  final List<String> warnings;

  const DecryptResultDto({
    required this.newGroupState,
    required this.event,
    this.sender,
    required this.warnings,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      event.hashCode ^
      sender.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          event == other.event &&
          sender == other.sender &&
          warnings == other.warnings;
}

/// Result of decrypting a push notification payload.
class DecryptedPush {
  /// DID of the message sender, extracted from their MLS credential.
  final String? senderDid;

  /// Human-readable preview for the notification body (truncated to 200 chars).
  /// `None` for protocol messages (commit, welcome, checkpoint) that should not
  /// generate a visible notification.
  final String? plaintextPreview;

  /// The MLS group ID the message belongs to.
  final Uint8List groupId;

  /// 16-byte message ID for deduplication (present for Message and Reaction events).
  final Uint8List? messageId;

  const DecryptedPush({
    this.senderDid,
    this.plaintextPreview,
    required this.groupId,
    this.messageId,
  });

  @override
  int get hashCode =>
      senderDid.hashCode ^
      plaintextPreview.hashCode ^
      groupId.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedPush &&
          runtimeType == other.runtimeType &&
          senderDid == other.senderDid &&
          plaintextPreview == other.plaintextPreview &&
          groupId == other.groupId &&
          messageId == other.messageId;
}

/// Result of signing a Drawbridge challenge.
class DrawbridgeChallengeSignature {
  /// Ed25519 signature (64 bytes)
  final Uint8List signature;

  /// Ed25519 public key (32 bytes)
  final Uint8List publicKey;

  const DrawbridgeChallengeSignature({
    required this.signature,
    required this.publicKey,
  });

  @override
  int get hashCode => signature.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DrawbridgeChallengeSignature &&
          runtimeType == other.runtimeType &&
          signature == other.signature &&
          publicKey == other.publicKey;
}

class EncryptResultDto {
  final Uint8List newGroupState;
  final Uint8List tag;
  final Uint8List ciphertext;

  /// The message_id assigned to the event (16 bytes for Message/Reaction, None otherwise)
  final Uint8List? messageId;

  const EncryptResultDto({
    required this.newGroupState,
    required this.tag,
    required this.ciphertext,
    this.messageId,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      tag.hashCode ^
      ciphertext.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          tag == other.tag &&
          ciphertext == other.ciphertext &&
          messageId == other.messageId;
}

/// Sent by the new device once the pair channel is up. `credential` reuses
/// [`CredentialDto`] rather than a new type.
class EnrollDto {
  final CredentialDto credential;
  final Uint8List stealthScanPubkey;
  final Uint8List ringKp;
  final List<OfferedKpDto> convKps;

  const EnrollDto({
    required this.credential,
    required this.stealthScanPubkey,
    required this.ringKp,
    required this.convKps,
  });

  @override
  int get hashCode =>
      credential.hashCode ^
      stealthScanPubkey.hashCode ^
      ringKp.hashCode ^
      convKps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrollDto &&
          runtimeType == other.runtimeType &&
          credential == other.credential &&
          stealthScanPubkey == other.stealthScanPubkey &&
          ringKp == other.ringKp &&
          convKps == other.convKps;
}

class EventDto {
  final EventKindDto kind;
  final Uint8List groupId;
  final BigInt epoch;
  final Uint8List payload;

  /// Unique message identifier (16 random bytes). Present for Message and Reaction events.
  final Uint8List? messageId;

  const EventDto({
    required this.kind,
    required this.groupId,
    required this.epoch,
    required this.payload,
    this.messageId,
  });

  /// Parse the payload as a reaction. Only valid when kind is Reaction.
  /// Returns None if this is not a Reaction event or if the payload is malformed.
  ReactionPayloadDto? reactionPayload() =>
      RustLib.instance.api.crateApiSimpleEventDtoReactionPayload(
        that: this,
      );

  @override
  int get hashCode =>
      kind.hashCode ^
      groupId.hashCode ^
      epoch.hashCode ^
      payload.hashCode ^
      messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          groupId == other.groupId &&
          epoch == other.epoch &&
          payload == other.payload &&
          messageId == other.messageId;
}

enum EventKindDto {
  message,
  commit,
  welcome,
  checkpoint,
  reaction,
  syncApp,
  ringMsg,
  unknown,
  ;
}

enum GroupKindDto {
  user,
  ring,
  ;
}

class ImageProcessResult {
  /// Processed image bytes (JPEG or PNG, resized if >2048px).
  final Uint8List imageBytes;
  final int width;
  final int height;

  /// ThumbHash bytes for blurry placeholder preview.
  final Uint8List thumbhash;

  /// MIME type: "image/jpeg" or "image/png".
  final String mimeType;

  const ImageProcessResult({
    required this.imageBytes,
    required this.width,
    required this.height,
    required this.thumbhash,
    required this.mimeType,
  });

  @override
  int get hashCode =>
      imageBytes.hashCode ^
      width.hashCode ^
      height.hashCode ^
      thumbhash.hashCode ^
      mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageProcessResult &&
          runtimeType == other.runtimeType &&
          imageBytes == other.imageBytes &&
          width == other.width &&
          height == other.height &&
          thumbhash == other.thumbhash &&
          mimeType == other.mimeType;
}

class KeyPackageResult {
  final Uint8List keyPackage;
  final Uint8List keyBundle;

  const KeyPackageResult({
    required this.keyPackage,
    required this.keyBundle,
  });

  @override
  int get hashCode => keyPackage.hashCode ^ keyBundle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageResult &&
          runtimeType == other.runtimeType &&
          keyPackage == other.keyPackage &&
          keyBundle == other.keyBundle;
}

/// One key package drawn from the same-user KP pool.
class OfferedKpDto {
  final Uint8List rkey;
  final BigInt seq;
  final Uint8List keyPackage;

  const OfferedKpDto({
    required this.rkey,
    required this.seq,
    required this.keyPackage,
  });

  @override
  int get hashCode => rkey.hashCode ^ seq.hashCode ^ keyPackage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OfferedKpDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          seq == other.seq &&
          keyPackage == other.keyPackage;
}

class OwnEventInputDto {
  final String rkey;
  final Uint8List ciphertext;

  const OwnEventInputDto({
    required this.rkey,
    required this.ciphertext,
  });

  @override
  int get hashCode => rkey.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OwnEventInputDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          ciphertext == other.ciphertext;
}

@freezed
sealed class PairingCommandDto with _$PairingCommandDto {
  const PairingCommandDto._();

  const factory PairingCommandDto.sendFrame({
    required Uint8List ciphertext,
  }) = PairingCommandDto_SendFrame;
  const factory PairingCommandDto.seedKpPool({
    required Uint8List deviceId,
    required List<OfferedKpDto> kps,
  }) = PairingCommandDto_SeedKpPool;
  const factory PairingCommandDto.publishRingCommit({
    required Uint8List tag,
    required Uint8List ciphertext,
  }) = PairingCommandDto_PublishRingCommit;
  const factory PairingCommandDto.surfaceApprovalPrompt({
    required String deviceName,
    required String did,
  }) = PairingCommandDto_SurfaceApprovalPrompt;
  const factory PairingCommandDto.persistRing({
    required Uint8List ringId,
  }) = PairingCommandDto_PersistRing;
  const factory PairingCommandDto.rosterReceived({
    required List<SiblingInfoDto> roster,
  }) = PairingCommandDto_RosterReceived;
  const factory PairingCommandDto.startSync() = PairingCommandDto_StartSync;
}

/// Decoded pairing code contents: rendezvous token + channel secret.
class PairingPayloadDto {
  final Uint8List token;
  final Uint8List secret;

  const PairingPayloadDto({
    required this.token,
    required this.secret,
  });

  @override
  int get hashCode => token.hashCode ^ secret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingPayloadDto &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          secret == other.secret;
}

@freezed
sealed class PairingUiStateDto with _$PairingUiStateDto {
  const PairingUiStateDto._();

  /// No pairing in flight. `PairingSessionHandle` itself never returns
  /// this — see the doc on the core `Idle` variant.
  const factory PairingUiStateDto.idle() = PairingUiStateDto_Idle;

  /// New device: code generated, waiting for the peer to enter it.
  const factory PairingUiStateDto.showingCode({
    required String code,
    required String uri,
  }) = PairingUiStateDto_ShowingCode;

  /// Existing device: code accepted, waiting for the peer's `Enroll`.
  const factory PairingUiStateDto.awaitingPeer() =
      PairingUiStateDto_AwaitingPeer;

  /// Existing device: `Enroll` received, waiting on the approve/reject
  /// decision.
  const factory PairingUiStateDto.awaitingApproval({
    required String deviceName,
    required String did,
  }) = PairingUiStateDto_AwaitingApproval;

  /// Enroll/Admit exchange complete. Says nothing about history sync —
  /// that stays observable via `syncStatus`.
  const factory PairingUiStateDto.done({
    required Uint8List ringId,
  }) = PairingUiStateDto_Done;

  /// Terminal failure, with a reason retained on the session rather than
  /// thrown away.
  const factory PairingUiStateDto.failed({
    required String reason,
  }) = PairingUiStateDto_Failed;
}

/// Reaction payload extracted from a Reaction event.
class ReactionPayloadDto {
  final String emoji;
  final Uint8List targetMessageId;

  const ReactionPayloadDto({
    required this.emoji,
    required this.targetMessageId,
  });

  @override
  int get hashCode => emoji.hashCode ^ targetMessageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReactionPayloadDto &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          targetMessageId == other.targetMessageId;
}

@freezed
sealed class RingCommandDto with _$RingCommandDto {
  const RingCommandDto._();

  const factory RingCommandDto.publishStealthEvent({
    required Uint8List tag,
    required Uint8List ciphertext,
  }) = RingCommandDto_PublishStealthEvent;
  const factory RingCommandDto.replenishKeyPackage() =
      RingCommandDto_ReplenishKeyPackage;
  const factory RingCommandDto.registerGroup({
    required Uint8List groupId,
    required GroupKindDto kind,
  }) = RingCommandDto_RegisterGroup;
  const factory RingCommandDto.pollForNewDevices() =
      RingCommandDto_PollForNewDevices;
}

@freezed
sealed class RingMsgDto with _$RingMsgDto {
  const RingMsgDto._();

  /// "I am missing history — open a sync channel with me at this token."
  /// `target_device_id` names one sibling; `None` is a broadcast.
  const factory RingMsgDto.syncRequest({
    required Uint8List token,
    Uint8List? targetDeviceId,
  }) = RingMsgDto_SyncRequest;

  /// "I have history you don't — join me." Always targeted.
  const factory RingMsgDto.syncOffer({
    required Uint8List token,
    required Uint8List targetDeviceId,
  }) = RingMsgDto_SyncOffer;

  /// "Here is what I hold", as a reference to an external blob. See
  /// `moat_core::RingMsg::HistorySummary` for why the list is not inline.
  const factory RingMsgDto.historySummary({
    required String uri,
    required Uint8List key,
    required Uint8List ciphertextHash,
    required BigInt ciphertextSize,
    required Uint8List contentHash,
  }) = RingMsgDto_HistorySummary;
}

/// Information about the sender of a message, extracted from MLS credentials.
class SenderInfoDto {
  /// The sender's DID (e.g., "did:plc:abc123")
  final String did;

  /// The sender's device name (format: "did:plc:xxx/Device Name")
  final String deviceName;

  /// The sender's stable 16-byte device id, from their MLS credential.
  final Uint8List deviceId;

  const SenderInfoDto({
    required this.did,
    required this.deviceName,
    required this.deviceId,
  });

  @override
  int get hashCode => did.hashCode ^ deviceName.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenderInfoDto &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          deviceName == other.deviceName &&
          deviceId == other.deviceId;
}

/// One existing sibling's identity + stealth address, carried in
/// `Admit.roster`.
class SiblingInfoDto {
  final Uint8List deviceId;
  final String deviceName;
  final Uint8List stealthPubkey;

  const SiblingInfoDto({
    required this.deviceId,
    required this.deviceName,
    required this.stealthPubkey,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ deviceName.hashCode ^ stealthPubkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SiblingInfoDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          stealthPubkey == other.stealthPubkey;
}

/// A sibling device's stealth address: the 32-byte X25519 scan pubkey plus the
/// stable 16-byte device id it belongs to.  Mirrors `moat_core::SiblingStealth`.
class SiblingStealthDto {
  final Uint8List scanPubkey;
  final Uint8List deviceId;

  const SiblingStealthDto({
    required this.scanPubkey,
    required this.deviceId,
  });

  @override
  int get hashCode => scanPubkey.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SiblingStealthDto &&
          runtimeType == other.runtimeType &&
          scanPubkey == other.scanPubkey &&
          deviceId == other.deviceId;
}

/// What a sibling last advertised, as this device recorded it.
class SiblingSummaryDto {
  /// Hex-encoded 16-byte device id.
  final String deviceId;
  final BigInt conversations;
  final BigInt messages;
  final PlatformInt64 receivedAtMs;

  /// Whether the user has already been asked about *this* advertisement.
  final bool dismissed;

  const SiblingSummaryDto({
    required this.deviceId,
    required this.conversations,
    required this.messages,
    required this.receivedAtMs,
    required this.dismissed,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      conversations.hashCode ^
      messages.hashCode ^
      receivedAtMs.hashCode ^
      dismissed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SiblingSummaryDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          conversations == other.conversations &&
          messages == other.messages &&
          receivedAtMs == other.receivedAtMs &&
          dismissed == other.dismissed;
}

class StealthKeypair {
  final Uint8List privateKey;
  final Uint8List publicKey;

  const StealthKeypair({
    required this.privateKey,
    required this.publicKey,
  });

  @override
  int get hashCode => privateKey.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StealthKeypair &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey &&
          publicKey == other.publicKey;
}

@freezed
sealed class SyncFailureDto with _$SyncFailureDto {
  const SyncFailureDto._();

  /// Requester: nobody joined the rendezvous before it expired.
  const factory SyncFailureDto.noAnswer() = SyncFailureDto_NoAnswer;

  /// Responder: the request expired before this device answered it.
  const factory SyncFailureDto.requestExpired() = SyncFailureDto_RequestExpired;

  /// This device's user declined a sibling's request.
  const factory SyncFailureDto.declined() = SyncFailureDto_Declined;

  /// The pair channel closed before the transfer finished.
  const factory SyncFailureDto.channelClosed({
    required String detail,
  }) = SyncFailureDto_ChannelClosed;

  /// The request could not be published to the ring at all.
  const factory SyncFailureDto.publishFailed({
    required String detail,
  }) = SyncFailureDto_PublishFailed;
}

/// A decrypted pair-WS sync frame: the `SyncMsg` bytes plus the device
/// that sent them.
///
/// The name comes from the MLS leaf credential, which is authenticated,
/// where a field in the payload would not be. It is what lets a finished
/// sync say *which* sibling the history came from — or, when nothing
/// moved, which one had no more than you.
class SyncFrameDto {
  final Uint8List payload;
  final String? senderDeviceName;

  const SyncFrameDto({
    required this.payload,
    this.senderDeviceName,
  });

  @override
  int get hashCode => payload.hashCode ^ senderDeviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncFrameDto &&
          runtimeType == other.runtimeType &&
          payload == other.payload &&
          senderDeviceName == other.senderDeviceName;
}

class SyncMessageDto {
  final String rkey;
  final Uint8List? messageId;
  final String senderDid;
  final String senderDeviceName;
  final PlatformInt64 timestampMs;
  final String content;
  final bool isOwn;
  final String? blobUri;
  final Uint8List? blobKey;
  final Uint8List? blobCiphertextHash;
  final BigInt? blobCiphertextSize;
  final Uint8List? blobContentHash;
  final String? blobMime;
  final int? blobWidth;
  final int? blobHeight;

  /// The image's blurry placeholder, shown while the blob downloads.
  final Uint8List? blobThumbhash;

  /// Emoji reactions on this message. Carried because the receiving
  /// device cannot rebuild them: reaction events predating its
  /// membership are not decryptable to it.
  final List<SyncReactionDto> reactions;

  const SyncMessageDto({
    required this.rkey,
    this.messageId,
    required this.senderDid,
    required this.senderDeviceName,
    required this.timestampMs,
    required this.content,
    required this.isOwn,
    this.blobUri,
    this.blobKey,
    this.blobCiphertextHash,
    this.blobCiphertextSize,
    this.blobContentHash,
    this.blobMime,
    this.blobWidth,
    this.blobHeight,
    this.blobThumbhash,
    required this.reactions,
  });

  @override
  int get hashCode =>
      rkey.hashCode ^
      messageId.hashCode ^
      senderDid.hashCode ^
      senderDeviceName.hashCode ^
      timestampMs.hashCode ^
      content.hashCode ^
      isOwn.hashCode ^
      blobUri.hashCode ^
      blobKey.hashCode ^
      blobCiphertextHash.hashCode ^
      blobCiphertextSize.hashCode ^
      blobContentHash.hashCode ^
      blobMime.hashCode ^
      blobWidth.hashCode ^
      blobHeight.hashCode ^
      blobThumbhash.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncMessageDto &&
          runtimeType == other.runtimeType &&
          rkey == other.rkey &&
          messageId == other.messageId &&
          senderDid == other.senderDid &&
          senderDeviceName == other.senderDeviceName &&
          timestampMs == other.timestampMs &&
          content == other.content &&
          isOwn == other.isOwn &&
          blobUri == other.blobUri &&
          blobKey == other.blobKey &&
          blobCiphertextHash == other.blobCiphertextHash &&
          blobCiphertextSize == other.blobCiphertextSize &&
          blobContentHash == other.blobContentHash &&
          blobMime == other.blobMime &&
          blobWidth == other.blobWidth &&
          blobHeight == other.blobHeight &&
          blobThumbhash == other.blobThumbhash &&
          reactions == other.reactions;
}

@freezed
sealed class SyncOutputDto with _$SyncOutputDto {
  const SyncOutputDto._();

  /// JSON-encoded `SyncMsg` ready to be encrypted via ring MLS and sent on the pair WS.
  const factory SyncOutputDto.send({
    required Uint8List bytes,
  }) = SyncOutputDto_Send;

  /// Persist these messages for the conversation `conv_id` (hex group ID).
  const factory SyncOutputDto.store({
    required String convId,
    required List<SyncMessageDto> messages,
  }) = SyncOutputDto_Store;
}

/// One emoji reaction, as carried by a synced message.
class SyncReactionDto {
  final String emoji;
  final String senderDid;

  const SyncReactionDto({
    required this.emoji,
    required this.senderDid,
  });

  @override
  int get hashCode => emoji.hashCode ^ senderDid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncReactionDto &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          senderDid == other.senderDid;
}

@freezed
sealed class SyncRequestUiStateDto with _$SyncRequestUiStateDto {
  const SyncRequestUiStateDto._();

  /// No sync request in flight. The handle itself never returns this;
  /// a host wrapping an optional session reports it when there is none.
  const factory SyncRequestUiStateDto.idle() = SyncRequestUiStateDto_Idle;

  /// Waiting on the rendezvous, in either role.
  const factory SyncRequestUiStateDto.awaitingPeer() =
      SyncRequestUiStateDto_AwaitingPeer;

  /// A sibling asked for history; this device's user has not decided.
  const factory SyncRequestUiStateDto.awaitingApproval({
    required String deviceName,
  }) = SyncRequestUiStateDto_AwaitingApproval;

  /// Channel up, transfer running.
  const factory SyncRequestUiStateDto.active() = SyncRequestUiStateDto_Active;

  /// Transfer finished, with what it moved and where from.
  const factory SyncRequestUiStateDto.complete({
    required SyncTallyDto tally,
    String? deviceName,
  }) = SyncRequestUiStateDto_Complete;

  /// Terminal failure, with the structured reason retained.
  const factory SyncRequestUiStateDto.failed({
    required SyncFailureDto reason,
  }) = SyncRequestUiStateDto_Failed;
}

/// What a finished sync took from its peer. See `moat_core::SyncTally`.
class SyncTallyDto {
  final BigInt messages;
  final BigInt conversations;

  const SyncTallyDto({
    required this.messages,
    required this.conversations,
  });

  static Future<SyncTallyDto> default_() =>
      RustLib.instance.api.crateApiSimpleSyncTallyDtoDefault();

  @override
  int get hashCode => messages.hashCode ^ conversations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncTallyDto &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          conversations == other.conversations;
}

class ThumbHashResult {
  /// Raw RGBA pixel data (width * height * 4 bytes).
  final Uint8List rgba;
  final int width;
  final int height;

  const ThumbHashResult({
    required this.rgba,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => rgba.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbHashResult &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba &&
          width == other.width &&
          height == other.height;
}

class TickInputsDto {
  /// Sibling key packages fetched from our own PDS (driver filters out our own).
  final List<Uint8List> keyPackages;

  /// Per-sibling stealth addressing: `scan_pubkey` paired with the stable
  /// `device_id` it belongs to.  Required for the ring driver to address
  /// steady-state `SiblingMsg` payloads at a specific sibling.  Callers
  /// should filter out their own device.
  final List<SiblingStealthDto> siblingStealth;

  /// Own-PDS events since `own_events_cursor`.
  final List<OwnEventInputDto> ownEvents;

  /// Our stealth scan private key (32 bytes).
  final Uint8List stealthPrivkey;

  /// Our DID.
  final String did;

  /// Our device name.
  final String deviceName;

  /// Identity key bundle.
  final Uint8List keyBundle;

  /// Wall-clock time (ms since epoch); used as `ring_created_at` for new rings.
  final PlatformInt64 nowMs;

  const TickInputsDto({
    required this.keyPackages,
    required this.siblingStealth,
    required this.ownEvents,
    required this.stealthPrivkey,
    required this.did,
    required this.deviceName,
    required this.keyBundle,
    required this.nowMs,
  });

  @override
  int get hashCode =>
      keyPackages.hashCode ^
      siblingStealth.hashCode ^
      ownEvents.hashCode ^
      stealthPrivkey.hashCode ^
      did.hashCode ^
      deviceName.hashCode ^
      keyBundle.hashCode ^
      nowMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TickInputsDto &&
          runtimeType == other.runtimeType &&
          keyPackages == other.keyPackages &&
          siblingStealth == other.siblingStealth &&
          ownEvents == other.ownEvents &&
          stealthPrivkey == other.stealthPrivkey &&
          did == other.did &&
          deviceName == other.deviceName &&
          keyBundle == other.keyBundle &&
          nowMs == other.nowMs;
}

class WelcomeResultDto {
  final Uint8List newGroupState;
  final Uint8List welcome;
  final Uint8List commit;
  final Uint8List groupId;

  const WelcomeResultDto({
    required this.newGroupState,
    required this.welcome,
    required this.commit,
    required this.groupId,
  });

  @override
  int get hashCode =>
      newGroupState.hashCode ^
      welcome.hashCode ^
      commit.hashCode ^
      groupId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WelcomeResultDto &&
          runtimeType == other.runtimeType &&
          newGroupState == other.newGroupState &&
          welcome == other.welcome &&
          commit == other.commit &&
          groupId == other.groupId;
}
